### ISSUE TITLE
Option to check images for a maximum size

### ISSUE THREAD

**Issue by rdeltour** [IDPF/epubcheck#195]
_From [galen.gr...@gmail.com](https://code.google.com/u/110718996376442532745/) on July 01, 2012 05:07:22_

Suggested a check to be added: note images that exceed the 2-million pixel limit of the Apple iBookstore as a warning, so we can see which images violate this size limitation -- something often not visible for ePubs created by export from programs like InDesign, so no local image files in the file system to be able to check through other means, plus programs like Sigil give no such metadata on images much less and logic around analyzing them. 

Could be a flag option, so only checked when specifically requested.

_Original issue: http://code.google.com/p/epubcheck/issues/detail?id=195_

**Comment by tofi86** [comment]
I'm closing this issue since we will never implement vendor specific checks. Please use a third-party tool like FlightDeck for it:

> _This is why we created FlightDeck. Retailer-specific requirements are constantly changing, and some require specialized testing tools like Apple Transporter. I don't think it makes sense for EpubCheck to include all of those tests._
> _@jstallent in https://github.com/IDPF/epubcheck/issues/717#issuecomment-267338470_
