### ISSUE TITLE
Confusing error "image is too short"

### ISSUE THREAD

**Issue by rdeltour** [IDPF/epubcheck#275]
_From [tobias.c...@gmail.com](https://code.google.com/u/113360544385786948097/) on May 31, 2013 23:34:40_

PROBLEM: The error message "image file XXX is too short" is very confusing.
It obviously has nothing to do with the size of the image but with the images header information.

`com.adobe.epubcheck.bitmap.BitmapChecker.java : line 78`

```
int rd = CheckUtil.readBytes(in, header, 0, 4);
if (rd < 4) {
	report.error(null, 0, 0, "image file " + path + " is too short");
``` 

SOLUTION:

At the moment I can't tell a better error message as I don't understand the deeper sense of this check. Does it mean the image / header is corrupt?
Or what else?
If someone can tell I'll patch this issue...

_Original issue: http://code.google.com/p/epubcheck/issues/detail?id=275_

**Comment by tofi86** [comment]
Fixed in 4.0 with B&N contribution.

Message is now: `[MED-004] Image file header may be corrupted.`
