### ISSUE TITLE
Not checking mimetype is uncompressed in Zip

### ISSUE THREAD

**Issue by rdeltour** [IDPF/epubcheck#303]
_From [adam.ret...@googlemail.com](https://code.google.com/u/117632015505805793587/) on September 17, 2013 13:12:06_

PROBLEM: The epubcheck tool does not check that the mimetype entry in the Zip file is uncompressed, i.e. it is not following this part of the spec - http://www.idpf.org/epub/30/spec/epub30-ocf.html#sec-zip-container-mime

RESULT: At the moment epubs where the mimetype is compressed in the Zip erroneously pass the epubcheck tool 

EXPECTED: If the mimetype is compressed in the epub, the epubcheck tool should fail the validation.

_Original issue: http://code.google.com/p/epubcheck/issues/detail?id=304_

**Comment by rdeltour** [comment]
I know this is old... but I couldn't reproduce. @adamretter would you still have a sample by any chance?

**Comment by KLDavies** [comment]
Resurrecting this rather old issue as we've recently encountered it issue ourselves and are able to provide some samples.

Attached [zip file](https://github.com/IDPF/epubcheck/files/594362/epub30_spec_files.zip) contains:
- **epub30-spec_uncompressed.epub** - EPUB 3.0 specification in EPUB 3.0 format, mimetype entry stored uncompressed
- **epub30-spec_compressed.epub** - EPUB 3.0 specification in EPUB 3.0 format, mimetype entry stored compressed
- **epub30-spec_uncompressed.epubcheck.xml** - epubcheck 4.0.1 output when run against file epub30-spec_uncompressed.epub
- **epub30-spec_compressed.epubcheck.xml** - epubcheck 4.0.1 output when run against file epub30-spec_compressed.epub

As the XML output shows, both epub files validate despite the mimetype entry being compressed in one of them. Viewing the "compressed" version in a hex editor shows an incomplete mimetype entry at byte offset 30, reading simply "mimetype".
