### ISSUE TITLE
TOC UID and OPF UID are set in different ways

### ISSUE THREAD

**Issue by tofi86** [IDPF/epubcheck#329]
Got this error today:
```
WARNING: EB_978-3-15-960333-9.epub/OEBPS/toc.ncx: meta@dtb:uid content
'urn:isbn:9783159603339 ' should conform to unique-identifier in content.opf:
'urn:isbn:9783159603339'
```

Note the whitespace at the end of `meta@dtb:uid` and the missing whitespace at the end of OPF UID.

This is `ncx.xml`:
```
<meta name="dtb:uid" content="urn:isbn:9783159603339 "/>
```
and this is `content.opf`:
```
<dc:identifier id="bookid" opf:scheme="ISBN">urn:isbn:9783159603339 </dc:identifier>
```

This is because the OPF UID is retreived with an additional `trim()` and the ncx UID isn't. Seems to be introduced by @tledoux in fcbb96d70e43225dc3eee12210ceb3b8e414bf8f when fixing issue #200 

Thomas, did you add the `trim()` method on purpose and just forgot it to add in NCX handling?
I don't want to add or remove one or the other without your feedback ;-)

**Comment by rdeltour** [comment]
I had a fresh look. It doesn't seem the spec actually requires the NCX metadata to match the OPF's. The ID equality check was already removed (or not working) in the 4.0 branch.

In any case, I re-implemented the ID equality check, now also detecting trailing and leading whitespace, and report them as USAGE-level messages. Push pending.
