### ISSUE TITLE
ePubCheck/iTunes Producer encryption.xml validation issue

### ISSUE THREAD

**Issue by atroia** [IDPF/epubcheck#337]
I had a client send me the error below that they received from iTunes Producer on their ePub file. From reading a moblereads forum post it looks like it can be related to mismatched font extensions, but in this clients ePub I had removed all the fonts and their references throughout except I forgot to remove the encryption.xml (from InDesign CC ePub export). When I run the file through ePubCheck (3.0.1) the file is valid with no errors, but iTunes Producer will not validate the file and throws the error below.

ERROR ITMS-9000 "filename.epub: Item referenced in encryption.xml could not be found in the OPF manifest” at Book (MZitmspBookPackage)"

**Comment by tofi86** [comment]
Closing this as outdated. Feel free to reopen the issue if necessary.
