### ISSUE TITLE
Add example XML to documentation of XML output

### ISSUE THREAD

**Issue by josteinaj** [IDPF/epubcheck#374]
https://github.com/IDPF/epubcheck/wiki/Extraction#xml-output

The documentation for the XML output simply refers to jhove.xsd. I don't think epubcheck uses the entire jhove grammar for its output, and it's not directly clear what each field in the output is filled with.

A complete example of XML output would probably help a lot in the way of documenting how the grammar is used.

**Comment by tofi86** [comment]
I added basic information and a link to an example file.
