### ISSUE TITLE
More detailed messages for OPF_057 and OPF_051

### ISSUE THREAD

**Issue by tofi86** [IDPF/epubcheck#461]
see #460 for intial discussion.

```
OPF_051=Image dimensions exceed recommended size.
OPF_057=Image file length exceeds recommended size.
```

"recommended sizes" should be specified in the messages itself.

**Comment by rdeltour** [comment]
Closing the issue since these messages are now `SUPPRESSED`.

**Comment by tofi86** [comment]
I'm okay with that solution.
