### ISSUE TITLE
javax.imageio.ImageIO considers JPEGs with a CMYK colorspace invalid

### ISSUE THREAD

**Issue by robfrawley** [IDPF/epubcheck#464]
An exception gets thrown (here [BitmapChecker.java#L137](https://github.com/IDPF/epubcheck/blob/master/src/main/java/com/adobe/epubcheck/bitmap/BitmapChecker.java#L137)) when trying to read in a JPEG with a CMYK colorspace. As far as I can tell, this is a know issue with javax.imageio.ImageIO. 

Please correct me if I am wrong, but I cannot find anything within the [OPS 2.0.1](http://www.idpf.org/epub/20/spec/OPS_2.0.1_draft.htm), [OPF 2.0.1](http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm), or [Core Media Types 3.0.1](http://www.idpf.org/epub/301/spec/epub-publications.html#sec-core-media-types) that prohibits JPEG images with a CMYK colorspace.

**Comment by robfrawley** [comment]
Wonderful! Thanks!

**Comment by rdeltour** [comment]
No prob, sorry for the long wait and thanks for the PR :+1:
