### ISSUE TITLE
language validation

### ISSUE THREAD

**Issue by madevelopers** [IDPF/epubcheck#495]
I was doing some random epub stuff recently and found out that epubcheck doesn't accurately validate the language text. For example, this snippet `<dc:language>ssenasdf</dc:language>`, is not an error even if it is clearly random text. However, epubcheck detects the error when it has 9 characters or more `<dc:language>ssenasdfooiuh</dc:language>`.

**Comment by tofi86** [comment]
Closed as duplicate of #702
