### ISSUE TITLE
EDUPUB - check for elements following end of a section

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#502]
Need to ensure that asides and other content isn't placed after the end of a section, including between subsections.

For example, the following are errors:

&lt;section>
   ...
   &lt;section>&lt;/section>
   &lt;aside>&lt;/aside>
&lt;/section>

&lt;section>
   ...
   &lt;section>&lt;/section>
   &lt;p>&lt;/p>
   &lt;section>&lt;/section>
&lt;/section>

The spec may need to be clearer on this point, as currently it only states that all content needs to be in section tags, when the intent was that once subsections are started you shouldn't intersperse any non-section elements. I'll open a separate issue in the WG tracker for that, though.

**Comment by rdeltour** [comment]
I integrated your schema improvements  in e1580b6782232aa9ff17790fca70fe484e325b19
