### ISSUE TITLE
EDUPUB - complete nav required

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#507]
The spec requires that all headings be represented in the toc nav.

**Comment by jstallent** [comment]
All heading elements in all content documents?

**Comment by mattgarrish** [comment]
To quote "a toc nav [ContentDocs301] with links to the full document heading hierarchy MUST be included in every EPUB Publication conformant to this profile."

http://www.idpf.org/epub/profiles/edu/spec/#h.lmfoatmvs6h7

**Comment by rdeltour** [comment]
I implemented this check in 2d34738bcf91d0c124d6be3416214468433a4baf.

@mattgarrish however, there's still an ambiguity:

- section [6.1 Table of Contents](http://www.idpf.org/epub/profiles/edu/spec/#h.lmfoatmvs6h7) says a `toc nav` MUST include links to the full document **heading hierarchy**.
- section [4.2 Sectioning](http://www.idpf.org/epub/profiles/edu/spec/#h.frvc45xf6cia) says sections SHOULD have a heading, i.e it's not required.

The spec may need to clarify that the `toc nav` MUST include links to the full **section hierarchy** instead?

What EpubCheck now does is count the `section` or `body` elements and check that the result is equal to the count of `nav doc` links. Hence some limitations:

- `toc nav` links are not resolved. It w/b pretty difficult to check that a link resolves to a section, as the element being pointed to can vary (section,  first heading, first element, second nested div, whatever really), not even thinking about CFI.
- heading-less sections are taken into account, thus varying a bit from the strict interpretation of 6.1.

I'm closing this issue for now, but feel free to reopen if the solution is not satisfactory.

**Comment by mattgarrish** [comment]
On the plus side, that prose is out-of-date now, as I also opened a bunch of issues in the last edupub iteration to fix some of those inconsistencies. The coming edupub draft attempts to better clarify where headings are needed (what we mean by structural hierarchy), including noting that non-linear spine items are not subject to the parsing. Another late addition was that article can be used in addition to section, so we kept the sutructural hierarchy name.

Anyway, I also agree that this requirement is onerous and problematic, both for producers and validation, so only commenting to note for the record that the issue is open for the next edupub draft:
https://github.com/IDPF/epub-revision/issues/564

**Comment by rdeltour** [comment]
I'm re-opening the issue to make sure I do not forget to update it when IDPF/epub-revision#564 is solved.

**Comment by rdeltour** [comment]
What's the status on this one? @mattgarrish  Can I remove from the `4.0` milestone until the EDUPUB spec issue is solved?

**Comment by mattgarrish** [comment]
It's still open as the edupub work had disbanded for the summer before we filed the bug.

I'm in favour of removing any checking from 4.0. Without clarification about how the check has to work given the potential pitfalls, I don't see the value in trying to enforce yet.

**Comment by rdeltour** [comment]
I've lowered the check to `USAGE` while waiting for the spec clarification.

**Comment by tofi86** [comment]
@mattgarrish can you clarify the state of this issue? do we need to raise the severity level again now that the spec matured?

**Comment by mattgarrish** [comment]
We ditched that requirement at some point. It's just a general recommendation to include links to all sections now. Probably not even worth a usage note.

**Comment by tofi86** [comment]
Thanks Matt! Leaving the USAGE for now so that no one needs to take action here. Closing the issue.
