### ISSUE TITLE
English localization needs minor grammatical improvements.

### ISSUE THREAD

**Issue by rkwright** [IDPF/epubcheck#514]
The English localization could stand some love as there are a number of minor grammatical errors.

For example, RSC_001 is  “The file foo.html is not found”, which is not correct English grammar.  It should be “The file foo.html could not be found” or “The file foo.html was not found”. There are several examples like this.

I will make changes in the properties file and push it as a pull request.

**Comment by rdeltour** [comment]
I applied `s/is not found/could not be found`  to the error messages. Also changed the `ePub` case into `EPUB`.
The commit will close this issue when it's pushed, feel free to reopen or submit a PR for any other wording improvements. Thanks!
