### ISSUE TITLE
Missing Resources Referenced from Manifest are reported multiple times

### ISSUE THREAD

**Issue by rkwright** [IDPF/epubcheck#516]
If one has an EPUB that references a resource from the manifest that isn't actually in the EPUB, this error gets reported over and over.  This occurs because there are multiple files that walk through the manifest and each one reports that the resource is missing.  

These include

* EpubCFIChecker
* EpubNavCheck
* EpubStyleSheetsCheck
* EpubHTML5StructureCheck
* EpubExtLinksCheckEpubCSSCheck
* EpubLangCheck
* EpubTextContentCheck
* EpubScriptCheck
* EpubSpanCheck
* NavChecker

Wouldn't it be better to check the manifest once and report each missing resource then in subsequent checks, simply skip the missing resources?

Note that all these get hit only for XHTML (as it appears to be a "valid" type in all the checkers).  If the file is CSS, for example, it will only be reported a couple of times.

**Comment by rdeltour** [comment]
Thanks for the report . Yes I wonder why these checkers duplicated the report... I commented the code wherever it seemed to make sense.
