### ISSUE TITLE
iframes highly discouraged?

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#524]
WARNING(HTM-036): .\epub30-test-0100.epub/EPUB/xhtml/content-fallbacks-001.xhtml(30,47): IFrames are highly discouraged.

iframes are the backbone of scriptable components and provide a way (albeit somewhat awful) of embedding out-of-band descriptions, among other uses.

Warning they're highly discouraged runs counter to actual use.

**Comment by rkwright** [comment]
Totally agree.  Especially now since iframes are essentially an intrinsic part of the EPUB Scriptable Components (i.e. widgets).  See http://www.idpf.org/epub/sc/pkg/,  section 3.3 Embedding Components
