### ISSUE TITLE
non-existent directory not noted

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#525]
A minor one this time, but...

If you validate using a bad file name, epubcheck notes the file could not be found. If you do the same using "-mode exp" on an unpacked directory, you just get a message that epubcheck exited with errors, but no message that the directory does not exist.

**Comment by tofi86** [comment]
This is fixed on the `master` branch and will ship with the next release.

I added a new message `Directory not found: '<dir>'`
