### ISSUE TITLE
Incorrect link model for collection metadata

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#526]
In package-30.rnc, the content model for the metadata is this:

opf.collection.metadata.content = opf.collection.dc.elems & opf.collection.meta* & opf.link*

But it should be referencing opf.collection.link.

**Comment by rdeltour** [comment]
Just noticed this issue. I believe the schema is correct: the collection section refines the `link` element **when it is a child of `collection`** only ; in other words, when a `link` element is used in collection metadata, it is specced by the same rules as links in the publication's metadata, and has the same content model.

Please reopen if you disagree.
