### ISSUE TITLE
clarify error about XML ID

### ISSUE THREAD

**Issue by TzviyaSiegman** [IDPF/epubcheck#533]
I received this error about ncx "Error while parsing file 'value of attribute "id" is invalid; must be an XML name without colons'." The ID in ncx was the same as the path to the content ("L1-ESN2014J-R12.xhtml#r12-sec-0003). The hash triggered the error. (Earlier IDs included hyphens, and no error reported). A clearer error message that does not single out colon would be helpful. There are many disallowed characters in XML IDs (http://www.w3.org/TR/REC-xml/#sec-common-syn).

**Comment by mattgarrish** [comment]
Hi Tzviya,

 

A colon is a valid character in an xml name, though; it's xml namespaces that assigns it a purpose. To exclude it as invalid, It has to be singled out.

 

Matt

**Comment by TzviyaSiegman** [comment]
Makes sense, but I git this error only on ids with hashes (abd no colons)

**Comment by mattgarrish** [comment]
Right, it's explaining the production rule you have to follow for them, not telling you what specific character is wrong. But you can't remove that exclusion without requiring people to go look up what an ID is supposed to conform to.

 

I don't think epucheck's ID validation rules try to single out the offending character(s), but I'll let others speak to whether that's feasible.

 

Matt

**Comment by rdeltour** [comment]
I don't think we can single out the offending character. As far as I know, this message is built in the 3d party RelaxNG schema validator (Jing).
Closing the issue as `wontfix`, feel free to reopen if you disagree!
