### ISSUE TITLE
error message repetition

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#535]
I had an entry for a missing file in the package document and got 10 errors for it:

Validating against EPUB version 3.0 - custom validation
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
Validating using EPUB version 3.0 rules.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.

**Comment by rdeltour** [comment]
I know this is old stuff, but if you have any sample to repro, that would help ;)

**Comment by mattgarrish** [comment]
Still getting with the latest build. All you have to do is add a manifest entry for any non-existent file. 

I'll send you a test file separately.

**Comment by rdeltour** [comment]
It seems to be a duplicate of #516.
