### ISSUE TITLE
Include file path info in uri field

### ISSUE THREAD

**Issue by bitsgalore** [IDPF/epubcheck#540]
Earlier this week I was running epubcheck on a large nested directory tree. While looking at some of the output I was surprised that the _uri_ field only gives the file name without its path. E.g.: 

```
<repInfo uri="whatever.epub">
```

Wouldn't it be better to include the full file path here as well (particularly helpful when working with directory trees)?

This applies to both 3.0.1 and the 4.0 pre-release.

**Comment by rdeltour** [comment]
I agree this may be a nice improvement (although it's unlikely that I will have the time to include it in 4.0).

**Comment by tofi86** [comment]
I added this in PR #737

```xml
<repInfo uri="/Users/tofi/dev/epubcheck/target/test-classes/com/adobe/epubcheck/test/package/interesting_paths_epub3.epub">
  <created>2017-01-02T18:10:42Z</created>
  …
  <properties>
     <property>
        <name>FileName</name>
        <values arity="Scalar" type="String">
           <value>interesting_paths_epub3.epub</value>
        </values>
     </property>
```

I also added a new Property with the plain FileName to be able to get the FileName without having to parse the `@uri` attribute.
