### ISSUE TITLE
Temporary generated file '.epub' is not being deleted after validation

### ISSUE THREAD

**Issue by lh84** [IDPF/epubcheck#543]
Hello, 
I'm not familiar with the source code of epubcheck. I'm just using it to validate my ePub files programmatically. But I noticed that epubcheck generates a hidden file called '.epub'. I guess this file is being used to check the ePub internally. I'de recommend to delete this file after validation. From my view of perspective it is just unnecessary to keep this file.

**Comment by rdeltour** [comment]
Can you please tell me the exact command you ran, and which version of EpubCheck? When validating an expanded EPUB (i.e. a directory), the packaged EPUB should only be saved when the `--save` option is used.

**Comment by lh84** [comment]
I guess it was my fault. Can't reproduce it by myself. Sorry. So you can delete/close the issue

**Comment by rdeltour** [comment]
ok, thanks for the quick answer :+1:
