### ISSUE TITLE
Not required to add content lists

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#544]
Sorry, I missed noting a late change to the edupub spec: the "should" to include loi/lot/loa/lov lists in the nav document was reduced to encouragement. As a result, the following warning is no longer applicable:

WARNING(NAV-007): .\English-Language-GCSE-for-AQA.epub/EPUB/Text/nav.xhtml(11,46): The Navigation Document should have a listing of tables (epub:type="lot") when content documents contain 'table' elements.

**Comment by rdeltour** [comment]
OK no problem I'll revet that to a USAGE message.
