### ISSUE TITLE
Does spine listing requirement apply to nav doc?

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#545]
If a landmark entry references the toc in navigation document:

&lt;li>&lt;a epub:type="toc" href="#toc">Table of Contents&lt;/a>&lt;/li>

But the navigation document is not listed in the spine, is it correct that this warning be issued:

WARNING(RSC-011): .\English-Language-GCSE-for-AQA.epub/EPUB/Text/nav.xhtml(52,52): Found a reference to a resource that is not a spine item.

It's not technically a requirement that the nav doc load in the spine.

**Comment by rdeltour** [comment]
You're right, it shouldn't be a WARNING....It should actually be an ERROR! Publications says

>  All EPUB Content Documents linked to from the EPUB Navigation Document must be listed in the `spine`

Right?

**Comment by mattgarrish** [comment]
Right, but that rule was added without consideration of this case (to address the CFI linking problem and a desire for all content documents to be in-spine).

Is it the case that landmarks must load in the content area of the reading system? I really don't know the answer, as we don't say.

But, if so, then you're right it should be an error. If not, since the nav doc can open outside of the spine as xhtml, and clicking the link could simply scroll you back up to the toc, is it really an error?

**Comment by rdeltour** [comment]
I would suggest that if the Nav Doc is not in the spine, then the `landmark nav` should not (must not, actually) link to it. RS all have a built-in way to render and access the Nav Doc anyway.

In other words, I think this Nav Doc rule makes sense, and s/b enforced as such in EpubCheck (making RSC-011 an ERROR).
This doesn't prevent opening a new `epub-rev` issue if you feel the rule is too restrictive. 

Agreed?

**Comment by mattgarrish** [comment]
Right, this is the wrong forum, and I'm not sure I care enough to pursue it. :)

It's a niche case, as no other content document gets spine exclusion.
