### ISSUE TITLE
implied index-entry-list not recognized

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#548]
Although the index spec is confusing on this, it appears to indicate that if an index-group has a single ul element then index-entry-list is implied:

> ... or (2) there must be only one child that contains entries and it must be a ul element whose epub:type attribute value will have the implied value of index-entry-list ...

(I don't understand what "will have" means here, though. Is it suggesting that explicitly declaring is illegal?)

I'm getting errors if the value is not explicitly declared, however, which seems to come from the html usage context (which looks incorrect) that states the opposite, that it has to be explicit:

> must contain one and only one element carrying the child semantic index-entry-list

**Comment by rdeltour** [comment]
Good catch, thanks. I agree the "will have" wording sounds weird, but I thing you got the gist in your first interpretation: if it's the single `ul` the property is implied but can still be set explicitly.

**Comment by rdeltour** [comment]
@mattgarrish do you have a test case? I can't reproduce here, the schema  does contain the [check for implied entries](https://github.com/rdeltour/epub-idx/blob/master/epub-idx-10.sch#L61)...

**Comment by rdeltour** [comment]
and btw, the HTML usage context 

> must contain one and only one element carrying the child semantic `index-entry-list`

is not incorrect: as I recall "carrying the child semantic" was our way of saying it had the property, whether implied or explicit.

**Comment by mattgarrish** [comment]
> "carrying the child semantic" was our way of saying it had the property, whether implied or explicit

That's awfully confusing. Whenever I see "carrying" used in markup it indicates that the feature must be present, so if I only looked at the usage context I'd expect I'd have to explicitly call out all the semantics.

I know this is the wrong forum, but the usage contexts would be clearer if they ended with ", whether explicit or implied".

But back on topic, when I validated the linear algebra sample in the edupub repo I got a whole host of these errors that only would go away if I added the semantic explicitly:
https://github.com/IDPF/edupub/tree/master/samples

**Comment by rdeltour** [comment]
> That's awfully confusing. Whenever I see "carrying" used in markup it indicates that the feature must be present, so if I only looked at the usage context I'd expect I'd have to explicitly call out all the semantics.
> 
> I know this is the wrong forum, but the usage contexts would be clearer if they ended with ", whether explicit or implied".

Right, in retrospect I agree.

Anyway, thanks for the sample, I could reproduce and locate the issue, which came from nested lists deep down in the structure. I'm on it :wink:
