### ISSUE TITLE
allow epubsc prefix without declaration

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#550]
Need to allow "epubsc:" prefixing of metadata properties for scriptable components.

I'll update the registry shortly.

**Comment by rdeltour** [comment]
Right. I had added the SC vocab but forgot to add it to the predeclared set.

**Comment by mattgarrish** [comment]
Ah, ya, I shouldn't have skimmed the error message. It was an unrecognized property not the prefix itself.

**Comment by rdeltour** [comment]
Yes, on double-check the `epubsc` prefix **is** pre-declared. So this issue is invalid correct?

I'm closing, feel free to reopen if I missed something.

**Comment by mattgarrish** [comment]
Nope, it is invalid. The error was that the vocabulary properties were not recognized, and if you're handling that...

**Comment by rdeltour** [comment]
The properties currently allowed are the 4 properties defined in the SC draft [3.2.4.3 Scriptable Component Properties](https://docs.google.com/document/d/183O0uUMmILXUrv6NeUQssUT5tn9haY65lKyTdiZ9gDg/edit#heading=h.vtht0y25t0mx), so I don't expect handling more than that, should I?

What is the property in question?

**Comment by mattgarrish** [comment]
Nope, what I discovered is that the example later in the spec has old property names and those are being copied/pasted into the samples by people. Didn't mean that you had something more to do; just an affirmation that all is good.
