### ISSUE TITLE
<img src='data:image/png;base64,...'> is reported as error

### ISSUE THREAD

**Issue by cayhorstmann** [IDPF/epubcheck#551]
I use data:image URIs and get an error like this:

$ java -jar epubcheck-4.0.0-alpha11/epubcheck.jar my.epub 
Validating against EPUB version 3.0 - custom validation
ERROR(RSC-001): my.epub/OEBPS/bjeo_6_ch06_sec09_03_int1.xhtml(44,8259): File 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAS8AAAFUCAYAAAB1O7raAAAACXBIWXMAABcRAAAXEQHKJvM...TkSuQmCC' is not found.

**Comment by rdeltour** [comment]
I believe this was fixed along with #420 (unreleased yet, but available in the `master` branch). Closing this as duplicate, please provide a sample file if you want me to double-check.
