### ISSUE TITLE
NullPointerException in 3.0.1

### ISSUE THREAD

**Issue by oneeyedjames** [IDPF/epubcheck#553]
I've been trying to version 3.0.1 and I'm getting this error:

$ java -jar epubcheck-3.0.1.jar content/ -mode exp
Epubcheck Version 3.0.1

java.lang.NullPointerException
    at com.adobe.epubcheck.util.Archive.createArchive(Archive.java:102)
    at com.adobe.epubcheck.tool.Checker.run(Checker.java:207)
    at com.adobe.epubcheck.tool.Checker.main(Checker.java:182)

The only match I've found online says this happens when trying to save the archive to an unwritable directory but I'm not attempting to save the archive and my CWD is writable in any case.

**Comment by tofi86** [comment]
Try using the `content/` die as the last argument, after the `-mode exp`

**Comment by oneeyedjames** [comment]
The order of the arguments doesn't appear to matter.

$ java -jar epubcheck-3.0.1.jar -mode exp content/
Epubcheck Version 3.0.1

java.lang.NullPointerException
	at com.adobe.epubcheck.util.Archive.createArchive(Archive.java:102)
	at com.adobe.epubcheck.tool.Checker.run(Checker.java:207)
	at com.adobe.epubcheck.tool.Checker.main(Checker.java:182)

**Comment by forkbeard** [comment]
I am seeing the same problem with -mode exp. The directory is definitely writable:

Epubcheck Version 3.0.1

java.lang.NullPointerException
        at com.adobe.epubcheck.util.Archive.createArchive(Archive.java:102)
        at com.adobe.epubcheck.tool.Checker.run(Checker.java:207)
        at com.adobe.epubcheck.tool.Checker.main(Checker.java:182)

The OS is Windows 7. The command is run from a bat file running as administrator. Java version "1.8.0_45" [Java(TM) SE Runtime Environment (build 1.8.0_45-b14), Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)].

**Comment by forkbeard** [comment]
The command seems to run with the -mode exp -save switches without the null-pointer exception 
when a target directory is explicitly supplied for the -save option and when all paths are fully qualified.  I couldn't paths relative to the current working directory (CWD) to work. I needed something like:

java -jar C:\opt\epubcheck-3.0.1\epubcheck-3.0.1.jar C:\temp\Q65321\epubpkg\ -mode exp -save C:\temp\Q65321\

This tool would be easier to use if it were better documented. Ideally, the tool would use CWD as the default for -save, much as ZIP utilities do when creating an archive of a subdirectory. But, in any case, the exception should be handled gracefully.

**Comment by rdeltour** [comment]
Thanks for pinpointing the issue, I'll look into it.

**Comment by rdeltour** [comment]
I couldn't repro with latest builds from the master (forthcoming `4.0` release). Removing the `4.0` label for now, please chime in if the issue persists after 4.0.

**Comment by tofi86** [comment]
Closing this as outdated. Feel free to reopen the issue if necessary.
