### ISSUE TITLE
epubcheck GUI

### ISSUE THREAD

**Issue by skreutzer** [IDPF/epubcheck#555]
I've developed a simple epubcheck GUI in Java (1.6 or higher): see https://github.com/publishing-systems/automated_digital_publishing/tree/master/epubcheck. As it is freely licensed (GNU AGPL 3 or any later version), you might consider shipping it with epubcheck, maybe with IDPF branding. Of course it still needs many improvements, at the other hand it checks EPUBs in directories recursively, i18n is already built in and the underlying workflow can be used for automatization (input and output provided in XML, so other tools can build upon it). epubcheck is expected in the $/epubcheck/epubcheck1/ directory, but the path to the .jar might be made configurable as well as the parameter settings in the future.

I also made a video: https://vimeo.com/132641131

**Comment by tofi86** [comment]
Added you to the list of third-party apps / GUI's in the epubcheck wiki: https://github.com/IDPF/epubcheck/wiki/GUI

**Comment by skreutzer** [comment]
I totally forgot that list, thank you for adding the entry. I don't know from my own experience, but as it is Java, it should run under Mac, too, right?

**Comment by tofi86** [comment]
> but as it is Java, it should run under Mac, too, right?

It's running on Mac OS X but I cannot choose files for validation. So won't add "Mac OS X" label at the moment.

**Comment by skreutzer** [comment]
OK. I wasn't aware of it, and because I don't own an Apple device, I'll have to wait till someone is willing to help troubleshooting in this environment. I guess it'll be just some kind of path separator or line break issue again, but who knows. See [related issue] (https://github.com/publishing-systems/automated_digital_publishing/issues/4).

**Comment by tofi86** [comment]
Closing this as outdated and out-of-focus of the EpubCheck project at the moment.

Please feel free to reopen this issue if you think we should check on it again...
