### ISSUE TITLE
warning if no selection attributes on 2..n rootfile

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#560]
It was also decided not to make selection attributes required because it could invalidate existing implementations when we integrate with ocf, but to keep as a should.

The schematron that @murata0204 submitted needs to be tweaked accordingly.

**Comment by murata0204** [comment]
At present, the warning message is "At least one rendition selection attribute should be specified for each non-first rootfile element, which represents a non-default rendition."  This sentence is merely a recommendation.  Is this good enough?
