### ISSUE TITLE
epubcheck complains about valid mimetype file

### ISSUE THREAD

**Issue by rkwright** [IDPF/epubcheck#562]
I have an EPUB that contains a perfectly valid mimetype file.  When I run it in the 3.0 epubchecker online, it complains about all the widget-specific markup (naturally), but not the mimetype file.  But when I run the current epubcheck (built from this repo), I get:

    ERROR(PKG-005): logger-demo-2.epub/logger-demo-2.epub(-1,-1): The mimetype file has an extra field of length 28. The use of the extra field feature of the ZIP format is not permitted for the mimetype file.

I checked the mimetype file in a hex editor and it is fine, per spec.

**Comment by rdeltour** [comment]
Could it be that the `mimetype` file is not first in the ZIP or is compressed? IIRC this check had been legitimately added after v3.0, to assert [this part of the OCF spec](http://www.idpf.org/epub/301/spec/epub-ocf.html#sec-zip-container-mime):

> The mimetype file additionally **must not** be compressed or encrypted, and there **must not** be an extra field in its ZIP header.

But it might be buggy. Would you have a test file for a repro?

**Comment by rkwright** [comment]
Turns out it was complaining about the extra "directory bits" that OSX includes with any file.  So does the command-line zip utility unless you use the -X ("exclude extra OSX directory bits").  Otherwise, the mimetype file itself is fine, but the zip directory entry which points to it has the extra directory bits.  Using the -X flag, all seems OK.

Closing this issue as pilot error...

**Comment by rdeltour** [comment]
OK! thx for the double-check.
