### ISSUE TITLE
Support for ITS 2.0 tags

### ISSUE THREAD

**Issue by pheyvaer** [IDPF/epubcheck#563]
The validator gives errors when using tags from [ITS 2.0](http://www.w3.org/TR/its20/). However, the use of these tags is valid HTML5. Hence, they should be considered valid by epubcheck.

During the [validation](https://validator.nu/) of HTML5, a schema for ITS 2.0 is loaded. Epubcheck should also check this schema when validating the epub.

**Comment by mattgarrish** [comment]
The ITS tags are an extension of HTML5 and EPUB only recognizes the extensions listed in the [HTML Extensions](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-xhtml-extensions) section of the Content Docs spec.

You need to open a request in the [3.1 issue tracker](https://github.com/w3c/publ-epub-revision/issues) to consider inclusion.

**Comment by tofi86** [comment]
If I understand correct, the issue can be closed, right?

**Comment by mattgarrish** [comment]
Yes, it needs to go through the WG first.
