### ISSUE TITLE
No error raised when clipBegin == clipEnd in SMIL file

### ISSUE THREAD

**Issue by pettarin** [IDPF/epubcheck#568]
According to the EPUB 3 Media Overlays spec:

http://www.idpf.org/epub/301/spec/epub-mediaoverlays.html#sec-smil-audio-elem

> The chronological offset of the terminating position [i.e., clipEnd value] must be after the starting offset specified in the clipBegin attribute.

Currently, EpubCheck does not report an error if a SMIL file has an element with `clipBegin` equal to `clipEnd`.

**Comment by rdeltour** [comment]
Right. Media Overlays is poorly implemented in EpubCheck. This won't happen in `4.0`, but I intend to tackle that in the next major milestone.

**Comment by tofi86** [comment]
I added a _very basic_ schematron check for equal values in PR #726

However, it seems that validating the SMIL timestamp syntax is a horrible nightmare as there are different syntaxes with the same meaning — e.g. `0:23:30`, `23:30` and finally `23.5min` are the same (_oh lord, why would someone standardize such a bullshit…_) and technically should trigger the equality check — but... yeah, you see, we would need to implement a timestamp parser in schematron to acomplish this task...

Hopefully people don't mix those different syntaxes in `@clipBegin` and `@clipEnd` so for now there's only a basic check...

@rdeltour @pettarin I will leave it at your decision whether to include the check anyways or to wait until we have built a better timestamp check...

**Comment by pettarin** [comment]
No longer interested, but thank you for the effort. Do whatever you like. Close the issue if you prefer.

PS: w.r.t. the _bullshit_, you might want to read https://github.com/IDPF/epub-revision/issues/579

**Comment by pettarin** [comment]
> Hopefully people don't mix those different syntaxes in @clipBegin and @clipEnd so for now there's only a basic check...

If I remember correctly, there is some test for that (either on purpose or accidentally...) in the EPUB test suite.

**Comment by tofi86** [comment]
> If I remember correctly, there is some test for that (either on purpose or accidentally...) in the EPUB test suite.

Nope, this is valid and doesn't trigger an error:
`<audio src="chapter1_audio.mp3" clipBegin="23.5min" clipEnd="0:23:34.223"/>`

> No longer interested, but thank you for the effort. Do whatever you like. Close the issue if you prefer.

Alright, thanks anyways for your report and for the link to the epub-revision discussion.

**Comment by pettarin** [comment]
I only referred to the fact that in the test suite (I seemed to remember 
that) there are SMIL files with mixed syntax (!), not that they are invalid.

All the best,

AP

**Comment by rdeltour** [comment]
@tofi86’s basic fix was merged. To be fully resolved, we'd need to implement full SMIL clock parsing, but this is a larger and separate issue.
