### ISSUE TITLE
identify source in teacher-edition

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#578]
If an edupub also has dc:type teacher-edition, it should include a source identifying the student edition.[1] Doesn't appear that we're checking this yet.

[1] http://www.idpf.org/epub/profiles/edu/spec/#h.tk8nwtxppt3c

**Comment by mattgarrish** [comment]
Sorry, disregard this. I was still validating the wcag sample in the epub3 samples while messing around in the edupub samples. Not a bug.

**Comment by rdeltour** [comment]
It should be reported as `RSC-017 A teacher's edition should identify the corresponding student edition in a dc:source element.`

**Comment by rdeltour** [comment]
Ah you beat me to it ;)

**Comment by mattgarrish** [comment]
I should have checked the schema, but took the lazy route and assumed a test by validation would be accurate... mea culpa
