### ISSUE TITLE
Consider ignoring prefix redeclarations to reserved URI

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#585]
Seems like it could become a nuisance warning, especially for rendition: which seems to be generated automatically by some software.

**Comment by rdeltour** [comment]
Right. It seems it's not even a SHOULD in the spec (which only says that it SHOULD NOT be overridden).

**Comment by mattgarrish** [comment]
Yes, it all kind of hinges on the interpretation of overridden, and I agree that simply redeclaring as reserved really doesn't constitute an override.

**Comment by eBookNoir** [comment]
@rdeltour mentioned using vanilla epubcheck, which i am guessing means from github the 4.0 version not from pagina. that worked to validate epub via another script i used, but you also have to remove <meta property="ibooks:specified-fonts">true</meta> or it won't validate with vanilla check either.

**Comment by tofi86** [comment]
I don't know what you mean with 'vanilla epubcheck'...

There should be no difference between the 4.0.0 release from github and the pagina EPUB-Checker 1.5 as it uses the exact 4.0.0 library internally...

**Comment by eBookNoir** [comment]
That was the wording i was given, I figured it must have meant just epubcheck via terminal and the java app. Either way the rendition warning is failing files, it shouldn't be. If removed, they then act as reflowable, so something somewhere is wrong.

**Comment by tofi86** [comment]
Alright, so the result from our Twitter discussion is, that pagina EPUB-Checker and Epubcheck are behaving the same. Good to know. Still, there's something wrong with the renditions property which should be further investigated in this thread...

**Comment by eBookNoir** [comment]
Agree, that something must be off if the file turns reflowable in apps because of rendition prefix removed. and specified-fonts has to be removed.

**Comment by mattgarrish** [comment]
It could well happen that the property gets ignored if the reading system resolves the CURIE to a full URI for comparison. If the rs doesn't recognize "rendition:" as automatically mapping to the stem "http://www.idpf.org/vocab/rendition/#" then it won't see the publication as having FXL properties.

Reserving the prefix to simplify authoring was the intention of the FXL group, and none of the rs vendors spoke up during the 3.0.1 revision that it was problematic for them, so odd (but not unexpected) that there would be a failure without an explicit declaration.

But this is why epubcheck shouldn't emit anything for a simple redeclaration.

**Comment by wattoo** [comment]
I'm sorry but I don't understand what I have to do.
I must send an epub 3 FXL on the ibooks store. And I have this problem with epubcheck.
So what can I do ?
If I delete "prefix="rendition: http://www.idpf.org/vocab/rendition/#"" my epub becomes reflowable on iPad.
And I'm afraid if I don't delete it, iTunes Producer will not accept my epub 3 FXL....

**Comment by jstallent** [comment]
Apple's Transporter validator will accept the file even though it has the
rendition redeclaration. Also, the other retailers have not, as far as I
know, updated to 4.0 yet, so you should not have problems with them, either.

---------------------------------------------------------------------------------------------------

*JOSHUA TALLENT*   |  Director of Outreach and Education
joshua@firebrandtech.com
978-225-2757
www.firebrandtech.com
www.ebookarchitects.com


*@jtallent*
*@ebookarchitects*
*@askburnie*

Pre-flight your EPUB files with FlightDeck. Validation, Retailer Acceptance
Grid, Metadata Editing, and more!
http://eBookFlightDeck.com <http://ebookflightdeck.com/>

**Comment by wattoo** [comment]
Thank you very very much !!!

So can you explain me something.
I want in my epub to delete the « faux page » shadow in the middle of my epub 3 FLX.
And I don’t find how to do this, can you help me ?

**Comment by ferformaat** [comment]
@jstallent  And what do we do when they will use the epubcheck version 4.0?
Could this be a 'wrong warning' in the checker - a fault in this version?

**Comment by jstallent** [comment]
@ferformaat my understanding based on what @mattgarrish says above is that this warning should not be happening in EPUBCheck 4.0, and that it should be fixed in the next update.

**Comment by rdeltour** [comment]
@ferformaat what @jstallent said above is correct, this will be fixed in v4.0.1, which will be released very soon.

**Comment by ferformaat** [comment]
Thanks a lot. Now I know I can't stop the investigation.
