### ISSUE TITLE
WARN on absolute positioned elements (CSS-017)

### ISSUE THREAD

**Issue by tofi86** [IDPF/epubcheck#589]
CSS rule `position: absolute;` throws 
```
WARNING (CSS-017) at "EB_978-3-426-41063-9.epub/OEBPS/stylesheet.css" (line 207, col 17):
   CSS selector specifies absolute position.
```

I think this is more likely a `USAGE` message rather than a `WARNING`. The EPUB spec doesn't forbid absolutely positioned elements, right?

**Comment by rdeltour** [comment]
> The EPUB spec doesn't forbid absolutely positioned elements, right?

It does, for non-FXL documents. See [CSS 2.1](http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-css-2.1) in the Content Doc spec:

> The `absolute` value of the `position` property **SHOULD** be used only with XHTML Content Documents whose `rendition:layout` property [Publications301] has been set to `pre-paginated`.

**Comment by tofi86** [comment]
Oh, sorry, wasn't aware of that...

**Comment by rdeltour** [comment]
no prob 😉

**Comment by vigneshkumarintegra** [comment]
whether the warning will be ignored by apple itunes validtor while uploading the ePub to iTunes store for selling
