### ISSUE TITLE
Localization updates for 4.0.0

### ISSUE THREAD

**Issue by tofi86** [IDPF/epubcheck#590]
Commit 38501281004fcd0145e9babb822285407f5092a8 only documentates the `-profile` switch for the english/default message properties file, but not for the localizations.

Localizations need to be updated by maintainers:
- [x] English
- [x] German (@tofi86, #599)
- [x] Japanese (@takahashim, #598)
- [x] Spanish (@Cuadratin, #612, #592)
- [x] French (@vincent-gros / @rdeltour, #625)
- [x] Dutch ([Merijn de Haen](https://www.transifex.com/user/profile/MerijnDeHaen/), #626)
- [ ] Italian (???)

**Comment by tofi86** [comment]
There are also another couple of new and changed text strings. Have a look at the Transifex system for epubcheck translation (#479, https://www.transifex.com/idpf/epubcheck/) to identify the new/changed text strings and create a PullRequest with your changes.

With a Transifex account you're able to either translate the strings in their webapp or identify the changed/new strings and add them to your PullRequest.

**Comment by tofi86** [comment]
when translating messages, especially in `com/adobe/epubcheck/messages/MessageBundle.properties`, make sure you have the **History** tab opened on the right in Transifex so you can see previous translations for the current message.

![bildschirmfoto 2015-09-09 um 23 19 34](https://cloud.githubusercontent.com/assets/365118/9774513/6fdc246c-5749-11e5-8775-92d0c5d51169.png)

This is useful in case @rdeltour only changed a word in the message but not the whole message itself...

**Comment by tofi86** [comment]
Japanese updates from PR #598 were suqashed and merged to `master` in 4c32d1b

**Comment by rdeltour** [comment]
Hi all. I'll prepare a bugfix release soon (say at the end of next week). I'd like to include any localization update contributed so far. Please let me know if there's anything ongoing before I release. And thanks all for the contribs!

**Comment by pettarin** [comment]
People from LIA/AIE stated that they will take care of the Italian translation (here and at Readium), so I am calling myself out of this task.

**Comment by rdeltour** [comment]
@pettarin ok, thanks for the info. Any contact info? Are they following this thread or the epubcheck list? I basically want to make sure they don't miss the 4.0.1 opportunity...

**Comment by pettarin** [comment]
It is not clear to me who is in charge of what over there. Asking the Italian member of the IDPF board might help. (If I remember correctly, it was their spoke person who tweeted me that they would have taken care.)

**Comment by rdeltour** [comment]
@pettarin ok, thanks!

**Comment by tofi86** [comment]
Just wrote messages to the other Transifex translatiors and asked for their contribution until Oct. 7

So last but not least asking @vincent-gros, @tledoux, @rdeltour whether the three of you see any chance to finish the french translation on Transifex? Thanks :)

**Comment by pettarin** [comment]
@rdeltour Sure, you are welcome. BTW, here in epubcheck (generic)you are using the "ping the prev translators/public call for translations (with deadline)" that I suggested for Readium ( https://github.com/readium/readium-js-viewer/pull/40#issuecomment-38809647 ) but AFAICT there it has not been adopted yet. Since I understand (DAISY)you are in both projects, you might want to push it forward. Just saying. Bye.

**Comment by vincent-gros** [comment]
@tledoux, @rdeltour I can finish the french translation this weekend if iit is needed.

**Comment by rdeltour** [comment]
> @tledoux, @rdeltour I can finish the french translation this weekend if iit is needed.

Great, thanks Vincent! Let me know if you need help...

**Comment by tofi86** [comment]
@vincent-gros Thanks! I think it's the best to finish the translation on Transifex. Otherwise you'll have to watch the file and character encoding closely, as some files are UTF-8 and some not and you would have to manually escape non-ASCII chars...

Let me know if I can help you with anything...

**Comment by rdeltour** [comment]
@tofi86 I finalized the french translation (it took a bit longer than expected, with all the new strings from Jing). let me know when you can integrate those!

**Comment by tofi86** [comment]
@rdeltour great! I can integrate the changes this evening. Stay tuned.

**Comment by tofi86** [comment]
I'm also adding the new Dutch translation by Transifex contributor [Merijn de Haen](https://www.transifex.com/user/profile/MerijnDeHaen/) also it's still missing the Jing messages.

Nevertheless, thanks Merijn! :tada:

**Comment by tofi86** [comment]
I'm closing this in favor of a quick 4.0.1 release and we're looking forward to integrate the italian translation in a next release.

**Comment by tofi86** [comment]
Waiting for translations for the only changed text string in 4.0.1:
https://github.com/IDPF/epubcheck/commit/39c93b23b9d31d68dfeb36768224d1f92a5edfa4#diff-d690896c18b58160491906e560600966L14

Updated:
en, fr, de, es

Pending:
ja, nl

**Comment by tofi86** [comment]
Pulled translations from Transifex and pushed the processed properties files with 406a200955bd5ce45aba64eb25093719d7ab4f10 to `master`
