### ISSUE TITLE
NCX Doctype in EPUB 3 is causing an ERROR

### ISSUE THREAD

**Issue by tofi86** [IDPF/epubcheck#591]
```
Validating using EPUB version 3.0.1 rules.

ERROR (OPF-073) at "dpi-test_EPUB3.epub/OEBPS/toc.ncx" (line 2, col 100):
   External identifiers must not appear in the document type declaration.
```

epubcheck 4.0.0 throws this ERROR when having a `toc.ncx` file with a DOCTYPE declaration for backwards compatibility in an EPUB 3 book:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ncx PUBLIC "-//NISO//DTD ncx 2005-1//EN" "http://www.daisy.org/z3986/2005/ncx-2005-1.dtd">
<ncx xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"
...
```

removing the doctype fixes the error, but why is the DOCTYPE forbidden?

**Comment by rdeltour** [comment]
> why is the DOCTYPE forbidden?

This comes from [XML Conformance](http://www.idpf.org/epub/301/spec/epub-publications.html#sec-xml-constraints) criteria in the Publications spec:

> External identifiers **must not** appear in the document type declaration.

**Comment by tofi86** [comment]
Okay, thanks...
