### ISSUE TITLE
Problem when validating package file with "package-30.nvdl"

### ISSUE THREAD

**Issue by raducoravu** [IDPF/epubcheck#601]
When validating a package file like:

            <package xmlns="http://www.idpf.org/2007/opf" xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dcterms="http://purl.org/dc/terms/" version="3.0" xml:lang="en"
                unique-identifier="bookid">
                <metadata>
                    <dc:title>Book title</dc:title>
                    <dc:language id="pub-language">en</dc:language>
                    <dc:identifier id="bookid">http://my-URI-stub/</dc:identifier>
                    <meta property="dcterms:modified">2012-02-20T22:17:24Z</meta>
             </metadata>
        .............

the error is reported:

       elements from namespace "http://purl.org/dc/elements/1.1/" are not allowed

The "package-30.nvdl" should add the ' useMode="attach"' attribute to all the "validate" references to the RNC schema and Schematron file.

Similar problem with "ocf-container-30.nvdl". In order to allow in the XML elements from other namespaces we need to use the attach mode.

**Comment by rdeltour** [comment]
@raducoravu thx for the report! Theses NVDLs are not used by EpubCheck, so no wonders this had not been detected earlier... Can you please review that PR #602 works for you?

**Comment by raducoravu** [comment]
Thanks Romain, the fixes look good to me. We also use the EPUB Checker schemas separately to validate XHTML 5 files opened from EPUB 3 archives and this is why we noticed the problem.
