### ISSUE TITLE
Parsing of meta in encoding declaration state should be case insensitive

### ISSUE THREAD

**Issue by raducoravu** [IDPF/epubcheck#603]
The XHTML document has something like:

            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

and Schematron validation "epub-xhtml-30.sch" complains:

        The meta element in encoding declaration state (http-equiv='content-type') must have the value 'text/html; charset=utf-8'

Should the validation be more relaxed and accept also "UTF-8" instead of "utf-8", maybe be more case insensitive?

**Comment by rdeltour** [comment]
Good catch, thanks Radu! :+1: 
I just checked the code and the `matches` call in Schematron does use the `i` flag for a case insensitive match... maybe it's a bug in Jing? I'll have a deeper look when time allows.

**Comment by rdeltour** [comment]
> the matches call in Schematron does use the i flag for a case insensitive match... maybe it's a bug in Jing?

Ouch, my bad. The `i` parameter was unquoted, and therefore evaluated as an empty sequence instead of the string `'i'` :confused:

**Comment by raducoravu** [comment]
Just reached the same conclusion on my side :+1:
