### ISSUE TITLE
SVG font validation issue

### ISSUE THREAD

**Issue by schaffer1969** [IDPF/epubcheck#605]
The epubcheck is throwing up a number of issues when validating svg font files.
It claims that the viewbox attribute is required, but from what I can make out the SVG 1.1 spec says it's optional

ERROR: OPS/fonts/d17bc040-9e8b-4397-8356-8153f4a64edf.svg(3,42): SVG ViewBox is missing on fixed format document.

**Comment by rdeltour** [comment]
This error should only be reported on Fixed Layout content. Would you have a full EPUB sample for me to reproduce locally?

**Comment by schaffer1969** [comment]
I've uploaded a basic example at the following link.
The content is fixed layout but the SVG fonts are not.

https://hmhco.box.com/s/fpy2zipql005fcthnysu8bnot1gz9fnv

**Comment by schaffer1969** [comment]
The content is fixed layout but the svg font is not
I've attached a basic example.
https://app.box.com/s/zkb2iqsvjsv29nzue41li6r8r3j87iki

**Comment by rdeltour** [comment]
thanks for the sample :+1: . I had a quick glance at the code and it seems that this check is enabled for all SVG content listed in the OPF when the whole EPUB is Fixed Layout; however I agree it shouldn't be enabled for SVG content not used as a Content Document (like fonts).

I'll have a deeper look when time allows.
