### ISSUE TITLE
font-face

### ISSUE THREAD

**Issue by Mus2659** [IDPF/epubcheck#607]
Hi,

I am facing issue in ePub checker 4.0, while validating the ePub fixed Layout file. The below warning messages are shown in the checker.

1. Re-declaration of reserved prefix 'rendition'.
2. font-face references OEBPS/fonts/fontname.otf refers to non-standard font type font/vnd.ms-opentype.

Looking for your help to clear this issue.

Thanks
Mustafa A

**Comment by rdeltour** [comment]
> font-face references OEBPS/fonts/fontname.otf refers to non-standard font type font/vnd.ms-opentype.

The font media type should be `application/vnd.ms-opentype` instead, as defined in Publications 3.0.1 [Core Media Types](http://www.idpf.org/epub/301/spec/epub-publications.html#sec-core-media-types).

Closing this issue as invalid, feel free to keep commenting in this thread if you disagree.

**Comment by Mus2659** [comment]
Hi,

Thanks for your clarification for font-face.

Could you also help me on the first issue.

1. Re-declaration of reserved prefix 'rendition'.

Looking for your help on this.

Regards,
Mustafa A

**Comment by mattgarrish** [comment]
See https://github.com/IDPF/epubcheck/issues/585

**Comment by Mus2659** [comment]
Thanks matt

**Comment by cpshanley** [comment]
Can we no longer use TTF fonts in ePUB? Something like this:

<item id="IBMPlexSans-Light" href="fonts/IBMPlexSans-Light.ttf" media-type="application/x-font-ttf"/>

Cheers

**Comment by mattgarrish** [comment]
> Can we no longer use TTF fonts in ePUB?

You can, but you need to use `font/ttf` or `application/font-ttf` for the media type.

The list of [core media types](https://www.w3.org/publishing/epub3/epub-spec.html#sec-cmt-supported) is in the 3.2 spec.

**Comment by cpshanley** [comment]
Hi Matt,

Thanks for coming back. I followed that link and it says:

`application/font-sfnt`

So just to be clear in my mind, do I use that, or can I use either of the following, as you suggest:

`application/font/ttf`

or

`application/font-ttf`

Thanks for your help!

**Comment by rdeltour** [comment]
The media type for True Type fonts needs to be either `font/ttf` (preferred) or `application/font-sfnt` 😊

**Comment by cpshanley** [comment]
You are a gentleman and a scholar. Cheers.

**Comment by cpshanley** [comment]
I'm using Oxygen XML Author, which validates against EPUBCheck 4.1.1 and getting the following error:

`[EPUBCheck 4.1.1]
Font-face reference OPS/fonts/Roboto-Light.ttf refers to non-standard font type application/font-sfnt.`

Same if I try `font/ttf`.

Do I simply ignore it? Thanks.

**Comment by rdeltour** [comment]
The list of Core Media Types was updated in EPUB 3.2, which is supported from EPUBCheck 4.2 onward.

I think the latest Oxygen XML Author includes a more recent version of EPUBCheck. You can also probably manually update the EPUBCheck version used in Oxygen, although I don't remember how to do it. I’d suggest you ask to Oxygen’s support team.

**Comment by mattgarrish** [comment]
> application/font-ttf

Oops, wasn't paying attention when I typed that in. Looks like it's all been sorted out, though. :)

**Comment by cpshanley** [comment]
Phew. Oxygen is currently using 4.1.1

So I ignored it.

Displays fine in KP3 and Calibre.

Thanks heaps for your help.
