### ISSUE TITLE
Fixed Layout File Text not view on iphone

### ISSUE THREAD

**Issue by Mus2659** [IDPF/epubcheck#613]
Hi,

I herewith attached my fixed layout file, where the text was not viewed in the iphone ios 9. Only the images are viewing in the iphone. On checking on ipad ibooks 3.2 the text was properly rendered on the image.

Please change the .jpg to .epub for the epub file attached. I am not able to attach the epub file in the attachment.

Please help on this.

Thanks
Mustafa A 

![1](https://cloud.githubusercontent.com/assets/14832077/10163250/33fc6944-66cf-11e5-9945-0b5dc4559a4c.jpg)

**Comment by rdeltour** [comment]
I'm not sure I understand what is the specific issue with EpubCheck here. Can you please elaborate? If you're instead seeking general help you should ask via other channels, like [IDPF's forums](http://idpf.org/forums)
