### ISSUE TITLE
ePubcheck 3 vs ePubcheck 4

### ISSUE THREAD

**Issue by michael-igp** [IDPF/epubcheck#614]
Hi,

I'm getting following errors when I validate the epub on new ePubcheck version 4.

1) WARNING: NOID.epub/OPS/css/NOID.css(54,25): CSS selector specifies absolute position.

2) ERROR: NOID.epub/OPS/s001-Chapter-001.xhtml(-1,-1): Content file has invalid language value at attribute xml:lang.

For the language error message, the html tag is like this:
html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="eng" xml:lang="eng"

In the past the same epub had validated with the epubcheck version 3. 

Kindly advice.

Thanks,
Michael

**Comment by rdeltour** [comment]
> 1) WARNING: NOID.epub/OPS/css/NOID.css(54,25): CSS selector specifies absolute position.

this comes from the [EPUB 3 CSS Profile](http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-css-2.1): "The `absolute` value of the `position` property should be used only with XHTML Content Documents whose `rendition:layout` property has been set to `pre-paginated`."

> 2) ERROR: NOID.epub/OPS/s001-Chapter-001.xhtml(-1,-1): Content file has invalid language value at attribute xml:lang.

You should use a two-character language code, e.g. `xml:lang="en"`. The language identification string must conform to rules defined in [IETF BCP 47](https://www.ietf.org/rfc/bcp/bcp47.txt).

**Comment by rdeltour** [comment]
Closing as invalid since these messages are legit. Feel free to reopen or comment on this thread if you disagree.
