### ISSUE TITLE
Error parsing meta tag should not be case sensitive

### ISSUE THREAD

**Issue by tklevenz** [IDPF/epubcheck#621]
I get the following error:

    toc.xhtml(3,76): Error while parsing file 'The meta element in encoding declaration state (http-equiv='content-type') must have the value 'text/html; charset=utf-8'

When my meta tag looks like this:

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

This is what Saxon generates when output method is set to xhtml. 
If output is xml and everything in meta is lowercase it validates fine.

**Comment by rdeltour** [comment]
is it happening with EpubCheck 4.0.0? It should have been fixed, see #603.

**Comment by rdeltour** [comment]
Sorry, I just realized it was actually fixed *after*4.0.0. It will be released in the upcoming 4.0.1 version. Closing this as duplicate.
