### ISSUE TITLE
Incorrect error reported by Schematron when validating HTML5 table

### ISSUE THREAD

**Issue by raducoravu** [IDPF/epubcheck#622]
I have an HTML table like:

                <table>
                        <thead>
                            <tr>
                                <th id="d3350e31"
                                    >dasd</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td headers="d3350e31 "
                                    >2</td>
                            </tr>
                        </tbody>
                    </table>

so the @headers attribute properly points to the @id defined on the th but it has an extra space at the end of the value.

The Schematron "epub-xhtml-30.sch" complains with:

        The headers attribute must refer to th elements in the same table.

In my opinion that particular assert should apply normalize() on the attribute value before calling tokenize because the specs says that if the string ends or starts with the separator, it will report it as a token.

**Comment by raducoravu** [comment]
And we should probably do this for all other tokenize() function usages.

**Comment by rdeltour** [comment]
Good catch, thanks Radu! I spotted one other instances that needed to be fixed. Other calls of `tokenize` were used to check the presence of a specific value, so empty tokens can be safely ignored.

**Comment by raducoravu** [comment]
Thanks for fixing this Romain.
