### ISSUE TITLE
Remove aria-describedat from html5-aria-30.rnc

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#624]
The attribute has been removed from the final draft of ARIA 1.1 and won't be reappearing in the future. We're going to add a note to 3.0.1 not to use it and will remove the section in 3.1.

See https://github.com/IDPF/epub-revision/issues/595

**Comment by rdeltour** [comment]
@mattgarrish should EpubCheck be proactive and report this in 4.0.1 already, or wait for the errata to be published?

**Comment by mattgarrish** [comment]
Yes, please put this in 4.0.1. I just have to confirm how the messaging will appear in 3.0.1, but it's out of ARIA and will be removed in 3.1.

I'm anticipating an in-place edit of content docs to add a warning so it's obvious to everyone not to use it. Will try to get the text finalized today.

**Comment by rdeltour** [comment]
> Yes, please put this in 4.0.1

OK. As a `WARNING`, correct?

If I simply remove the attribute from the RelaxNG schema (as suggested in this issue's title), it will be reported as an `ERROR`, which may be too strict given that it was allowed in previous versions of the spec. WDYT?

**Comment by mattgarrish** [comment]
Well, this is the problem. It wasn't allowed before 3.0.1, so we're "deprecating" something that's never really existed in a usable form. It was added based on a draft of aria that's now destined to never be implemented.

To me, we should make it an error to use as we don't want anyone thinking it's usable, but I'm okay if we leave as a warning until 3.1. What's your take @mgylling?

**Comment by mgylling** [comment]
Yes, a warning sounds like the best approach until 3.1. 

/markus
