### ISSUE TITLE
library seems to be missing in zip-file for 4.0.1 release

### ISSUE THREAD

**Issue by TomvanEes** [IDPF/epubcheck#646]
I downloaded the zip file for the 4.0.1 release and created a small test application using the library.
Using the default constructor new EpubCheck(file), I do get a number of messages indicating that my epub has problems.
Next I get an exception:
```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.Iterables.tryFind(Ljava/lang/Iterable;Lcom/google/common/base/Predicate;)Lcom/google/common/base/Optional;
	at com.adobe.epubcheck.ocf.OCFChecker.runChecks(OCFChecker.java:330)
	at com.adobe.epubcheck.api.EpubCheck.doValidate(EpubCheck.java:215)
	at com.adobe.epubcheck.api.EpubCheck.validate(EpubCheck.java:189)
	at nl.davinci.epubtools.quality.EpubsChecker.processFolder(EpubsChecker.java:38)
	at nl.davinci.epubtools.quality.EpubsChecker.check(EpubsChecker.java:24)
	at nl.davinci.epubtools.EpubTools.run(EpubTools.java:316)
	at nl.davinci.epubtools.EpubTools.main(EpubTools.java:342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```
Although I had a try-catch around the instantiation and the method invocation of validate(), the main application did not get the chance to catch the exception. Trying to find the jar file that seems to be missing I got to google-collect-1.0.jar, but that seems not to fix the problem

**Comment by rdeltour** [comment]
From the stack trace, it seems your Java classpath is not configured properly. All the libraries in the `lib` folder must be in your classpath.

**Comment by TomvanEes** [comment]
I am not sure: the commandline generated by IntelliJ looks like:
"C:\Program Files\Java\jdk1.7.0_55\bin\java" -Didea.launcher.port=7532 "-Didea.launcher.bin.path=D:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 13.1.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.7.0_55\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\jce.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\jfxrt.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\resources.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\rt.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.7.0_55\jre\lib\ext\zipfs.jar;D:\Data\TVEData\javaProjects\EpubTools\out\production\EpubTools;D:\Data\TVEData\javaProjects\EpubTools\lib\commons-cli-1.2.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epublib-core-3.1.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\lucene-analyzers-common-5.1.0.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\lucene-core-5.1.0.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\lucene-queries-5.1.0.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\lucene-queryparser-5.1.0.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\lucene-codecs-5.1.0.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\tika-app-1.8.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\epubcheck.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\common-image-3.1.2.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\common-io-3.1.2.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\common-lang-3.1.2.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\commons-compress-1.5.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\google-collect-1.0.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\guava-14.0.1.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\imageio-core-3.1.2.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\imageio-jpeg-3.1.2.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\imageio-metadata-3.1.2.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\jackson-core-asl-1.9.12.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\jackson-mapper-asl-1.9.12.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\jing-20120724.0.0.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\sac-1.3.jar;D:\Data\TVEData\javaProjects\EpubTools\lib\epubcheck-4.0.1\lib\Saxon-HE-9.5.1-5.jar;D:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 13.1.4\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain nl.davinci.epubtools.EpubTools -checkepubs -epubfolder D:\Data\TVEData\javaProjects\EpubTools\christiedocs -output D:\Data\TvEData\javaprojects\EpubTools\christiechecks_{timestamp}.txt

(I added google-collect-1.0.jar because internet seemed to suggest that this jar file contained the class on which the classnotfoundexception was generated

**Comment by rdeltour** [comment]
you shouldn't add the `google-collect-1.0.jar` library, the `com.google.common.collect` package is part of Google Guava (version 14.0.1 of which is used by EpubCheck and included in the `lib` directory).
I suppose that adding the old `google-collect` library is what causes the compile issue, since the google API has changed in more recent version of Guava.

**Comment by TomvanEes** [comment]
I removed the file from the lib folder and removed the file from the lib setup in IntelliJ and still encounter the same problem. I further checked whether all files in the lib plus epubcheck.jar are added individually to the lib setup in IntelliJ.

**Comment by rdeltour** [comment]
EpubCheck dependencies are listed in the [Maven POM file](https://github.com/IDPF/epubcheck/blob/v4.0.1/pom.xml#L158-L223).

If you share a pointer to the code you're trying to run, I might have a look when time allows, but I do feel that you have a classpath configuration issue rather than there is something wrong with EpubCheck.

I'm closing this issue, feel free to keep commenting on this thread or reopen if you do think something is actually wrong on our side.
