### ISSUE TITLE
EPUB Check Java code depends on specific Saxon 9.5 class

### ISSUE THREAD

**Issue by raducoravu** [IDPF/epubcheck#647]
So sometimes when using EPUB validation with more recent versions of Saxon (9.6.0.7 in our case) we obtain:

```
        java.lang.ClassNotFoundException: net.sf.saxon.om.Name10Checker
            at java.net.URLClassLoader.findClass(Unknown Source)
            at java.lang.ClassLoader.loadClass(Unknown Source)
            at ro.sync.util.LateDelegationClassLoader.java.lang.Class loadClass(java.lang.String, boolean)(LateDelegationClassLoader.java:0)
            at java.lang.ClassLoader.loadClass(Unknown Source)
            at com.adobe.epubcheck.vocab.PrefixDeclarationParser.parsePrefixMappings(PrefixDeclarationParser.java:105)
            at com.adobe.epubcheck.vocab.VocabUtil.parsePrefixDeclaration(VocabUtil.java:183)
            at com.adobe.epubcheck.opf.OPFHandler30.startElement(OPFHandler30.java:145)
            at com.adobe.epubcheck.xml.XMLParser.startElement(XMLParser.java:542)
            at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
            at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
            at org.apache.xerces.impl.XMLNSDocumentScannerImplXerces$NSContentDispatcher.scanRootElementHook(Unknown Source)
            at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(
```

**Comment by rdeltour** [comment]
Oh, it seems `Name10Checker` has been renamed to `NameChecker` in 9.6, more details in the [class Javadoc](http://www.saxonica.com/documentation/#!javadoc/net.sf.saxon.om/NameChecker).

I suppose that to cover both versions we'll have to use reflexion...

**Comment by raducoravu** [comment]
How about if you use org.apache.xerces.util.XMLChar.isValidNCName instead?

**Comment by rdeltour** [comment]
> How about if you use org.apache.xerces.util.XMLChar.isValidNCName instead?

Xerces is not used explicitly as a 3d party dependency, so I suppose EpubCheck uses the JVM's internal version of it (exposed in a  `com.sun` package).

Anyway, on 2nd look it seems Saxon's `NameChecker` can be accessed via the `Configuration` object too, which would work with both 9.5 and 9.6.

**Comment by raducoravu** [comment]
If Xerces is not explicitly listed as a dependency, indeed sometimes EpubCheck might use the Xerces bundled with Java, sometimes like in the case of our application (Oxygen XML Editor) it will use the Xerces libraries which come with Oxygen. Another approach would be to copy the entire isValidNCName implementation from the Saxon or Xerces code to a class in the checker and remove the dependencies.
There seem to be other explicit dependencies on Saxon. Some seem to be extension function definitions which should be OK because they are API.

**Comment by tofi86** [comment]
@rdeltour I just had a look at this and couldn't find a way to support both saxon 9.5 and 9.6 – though I didn't try Reflexions yet...

Why would you like to maintain support for both Saxon versions anyways?

**Comment by tofi86** [comment]
Upgrade of Saxon to 9.7 has also been requested in #674

**Comment by mkraetke** [comment]
see my comment in #674

**Comment by tofi86** [comment]
Thanks Martin!

I would really like to update this with the next minor release.

@rdeltour Question from above again: Why would you like to support multiple Saxon versions anyways? Is there a specific reason?

If not, @mkraetke could make a PR for this...

**Comment by tofi86** [comment]
@mkraetke sent a PullRequest with those changes today (see #767) which upgrades the Saxon dependency to 9.6.0-7 and drops Saxon 9.5 compatibility.

Thanks, Martin!

@rdeltour I'm asking my question from above again: Why would you like to support multiple Saxon versions anyways? Is there a specific reason? I would be fine with supporting just Saxon 9.6 and later.

**Comment by tofi86** [comment]
FYI: We will update to Saxon 9.6.0-10 soon with PR #767. Thanks for your contribution @mkraetke!

Is there a specific need by someone (@raducoravu / @oxygenxml ?? ) to update further to 9.7 or 9.8? If so, let's discuss it in #674.

**Comment by raducoravu** [comment]
Oxygen XML Editor 19.1 will come bundled with Saxon 9.7.0.19 and EPUB Checked 4.0.2 (just as 19.0 did). Until now we have been patching a couple of EPUB Checker classes which did not work with 9.7 (having copies of the same classes which were rewritten to be compatible with 9.7 in our own JAR library).
So we had our workarounds for this.... but probably when the next EPUB Checker version is released we can remove our patches as EPUBChecker will work out of the box with Saxon 9.7.x.x.

**Comment by tofi86** [comment]
Okay, thanks for the information. I'm going to cross-post this statement in #674 and assigned the ticket to the 4.1 milestone in order to discuss a second Saxon update to 9.7.

Closing this as I'm merging PR #767 now.

**Comment by tofi86** [comment]
Note: The Saxon dependency was updated to 9.8.0-8 with PR #830 by @mkraetke. Thanks!
