### ISSUE TITLE
Error HTM-046 on item <item properties="nav"...> that is not listed in spine.

### ISSUE THREAD

**Issue by titusz** [IDPF/epubcheck#648]
EpubCheck 4.x gives us a new error on a huge amount of legacy EPUB3 Fixed Layout documents.
The nav documents are **not** included in the spine and convey only semantic information to the reading device without being intended to be shown as fixed layout page/document. Yet epubcheck 4.x complains with an error, that the vieport must be defined. Is this intended behaviour or can this be classified as a bug?

**Comment by mattgarrish** [comment]
Sounds like a bug in epubcheck, as the viewport only has to be set for spine items. From the rendition:layout section:

When the rendition:layout property [PackageVocab] is specified on a meta element, it indicates that the paginated or reflowable layout style applies globally for the EPUB Publication (i.e., for all spine items).

and

When the property is set to pre-paginated for a spine item, its content dimensions must be set as defined in Fixed-Layout Documents [ContentDocs301] .

http://www.idpf.org/epub/301/spec/epub-publications.html#fxl-property-layout-usage

**Comment by titusz** [comment]
I checked more closely and the case is more specific. The rendition:layout property is set globaly on a meta element. The nav document is listed in the spine with linear="no" and it is not linked to from anywhere and also has no explicit rendition:layout property. This was fine in epubcheck 3.x but generates an error in 4.x. I guess we can call this an edge case. We will change this for future productions. But what about the ca. 10k legacy productions that are out in the wild... will they all go invalid with epubcheck 4?

**Comment by mattgarrish** [comment]
Setting linear=no doesn't exempt a document as a reading system can still present it where it occurs in the spine even if nothing links to it. When that happens, for all the reading system knows it's just another fixed layout document. If you want it treated as reflowable, you need to put a spine override on the itemref (rendition:layout-reflowable).

The specification requirement didn't change from epubcheck 3 to 4 - and the requirement was in the original fxl information document - so it's probably a case that someone fixed some looseness in validation. I can't to speak to that, though.

**Comment by rdeltour** [comment]
> The rendition:layout property is set globaly on a meta element
and 
> The nav document is listed in the spine (...) and also has no explicit rendition:layout property.

the above statements seems to indicate that in this case EpubCheck is right reporting the absence of viewport as an error, so yes I assume similar content will be invalid in EpubCheck 4.x. 
AFAIR this conformance criterion was not checked by previous versions of EpubCheck.

You can always try to override the `rendition:layout` property or remove the Nav Doc from the spine, but I'm afraid there's nothing you can do to make existing content pass the new EpubCheck.

**Comment by tofi86** [comment]
Closing this as invalid after @rdeltour explained the current validation behaviour.
