### ISSUE TITLE
Undeclared prefix: rendition. This error occurs 3 times

### ISSUE THREAD

**Issue by vigneshkumarintegra** [IDPF/epubcheck#649]
While trying to upload the files in itunes stores  the below errors occurs. 
Can anyone suggest how to close the below issue. I searched but i can't find the solution for the same.

ERROR ITMS-9000: "xxxxxxxxxxxxxxxx.epub: OEBPS/package.opf(18): Undecleared prefix: rendition. This error occurs 3 times.  (For more information refer to http://support.apple.com/kb/HT6213)" at Book.

The ePub was validated against the  latest ePub checker (4.0.1) and the ePub is also sucessfully validated

Thanks in Advance.
Vignesh

**Comment by mattgarrish** [comment]
Please note that the issue tracker is for bugs in epubcheck. If you have general validation problems, please use the IDPF forums at http://www.idpf.org/forums

In this case, though, all you need to do is declare the prefix on the package element like so:

<package ... prefix="rendition: http://www.idpf.org/vocab/rendition/#">

The prefix was required prior to epub 3.0.1 and Apple undoubtedly hasn't moved their internal validation up to the lastest epubcheck yet. It's safer and simpler just to declare the attribute for the time being.
