### ISSUE TITLE
ePUB Checker 4.0 Warning

### ISSUE THREAD

**Issue by Sudhakar2007** [IDPF/epubcheck#651]
Hi,

I am facing issue in ePub checker 4.0, while validating the ePub fixed Layout file. The below warning messages are shown in the checker.

1. WARNING(RSC-018): ISBN_epubalt.epub/OEBPS/xhtml/CHP001.xhtml(781,61): A ltimg file 'si1.gif' could not be found.

Looking for your help to clear this issue.

Thanks
Sudhakar Haridoss

**Comment by tofi86** [comment]
This issue tracker is for bugs in EpubCheck, not for support on how to solve problems with your epub files! Please have a look at the IDPF forums http://idpf.org/forums when searching for help.

Regarding your problem: have a look in `CHP001.xhtml` at line 781 at char 61 to find the cause of the warning.

**Comment by Sudhakar2007** [comment]
Thanks very much.
