### ISSUE TITLE
Re-declaration of reserved prefix 'rendition'

### ISSUE THREAD

**Issue by JonathanMagus** [IDPF/epubcheck#654]
A test file of mine that previously validated correctly with epubcheck now gives this error: 

Re-declaration of reserved prefix ‘rendition’

when the opf contains: 

prefix="rendition: http://www.idpf.org/vocab/rendition/#

This appears to be already covered by the explanation given here though doesn’t seem to have been logged as an epubcheck issue as intended:

http://idpf.org/comment/1330#comment-1330 

Apologies if I am wrong about this.

**Comment by rdeltour** [comment]
This should have been fixed in EpubCheck v4.0.1. See #585 and #632.

What version of EpubCheck are you using?

**Comment by JonathanMagus** [comment]
Ah! I had version 4.0 not version 4.0.1. That explains it. Sorry.

I see it has been taken care of already.

Thanks.

**Comment by rdeltour** [comment]
> Ah! I had version 4.0 not version 4.0.1. That explains it. Sorry.

No prob. I'm closing the issue then.
