### ISSUE TITLE
error/warning count in output

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#655]
I was just doing some work on generating an epub from the specs and got to thinking it would be nice to see the total error/warning count after the message that the file contains errors.

When I'm tweaking xslts, it's not always clear if I've fixed the problem without scrolling back through all the messages output to the console. A count would at least give me a quick visual whether things have gotten better, worse or stayed the same.

Anyway, another of my non-critical feature requests...

**Comment by tofi86** [comment]
While this is very easy to implement as `Check finished with 5 warnings`, it may break all those tools which rely on or grep the message `Check finished with warnings` / `Check finished with errors`.

Therefore I would suggest to include a message counter at the very end like this:

**Current:**
```
…

Check finished with errors

epubcheck completed
```

**Suggestion:**
```
…

Check finished with errors

0 fatal errors
3 errors
5 warnings
2 informations
10 usage messages

epubcheck completed
```

or in a one-liner:
```
messages: 0 fatal errors / 3 errors / 5 warnings / 2 informations / 10 usage messages
```

What would you prefer, @mattgarrish?

**Comment by mattgarrish** [comment]
I'd vote to save space and go with the latter. The more actual errors you can read from the command line without scrolling the better.

You could maybe save some further space by trimming to:

> messages: 0 fatal / 3 errors / 5 warnings / 2 informational / 10 usage
