### ISSUE TITLE
OPF: undeclared prefix: rendition

### ISSUE THREAD

**Issue by attilavago** [IDPF/epubcheck#662]
*Issue 1 (see attachment too)

`ERROR: OPS/content.opf(37,35): Undecleared prefix: rendition
ERROR: OPS/content.opf(38,40): Undecleared prefix: rendition
ERROR: OPS/content.opf(39,35): Undecleared prefix: rendition`

This error seems to be generated by the following:

![screen shot 2015-12-11 at 12 01 34 p m](https://cloud.githubusercontent.com/assets/6254855/11743400/fab22d40-9ffe-11e5-8502-7448b3fb6b70.png)

`<meta property="media:duration" refines="#pageback_smil">00:02</meta>
<meta property="media:duration" refines="#pagefront_smil">00:06</meta>`
empty line here
`<meta property='rendition:layout'>pre-paginated</meta>
<meta property='rendition:orientation'>auto</meta>
<meta property='rendition:spread'>both</meta>`

If the empty line is removed, the error disappears. Looks like a parsing bug to me.

*Issue 2
This is a very small one but there's a typo there: "undecleared" should be "undeclared".

**Comment by rdeltour** [comment]
Are you running latest version v4.0.1? Could you share the OPF or a sample EPUB to help us reproduce the error? Thanks.

**Comment by attilavago** [comment]
Sorry, had a short day at the office on Friday. Please find attached the OPF file. As far as we know, we do run the latest version.
[samplecontent.opf.zip](https://github.com/IDPF/epubcheck/files/61047/samplecontent.opf.zip)

**Comment by rdeltour** [comment]
I cannot reproduce the error with the given sample:

```
$ epubcheck -m opf -u  samplecontent.opf
No errors or warnings detected.
epubcheck completed
```

Can you make sure you're running EpubCheck v4.0.1? If yes, maybe you can share a full EPUB?
Also, how do you get the error, running EpubCheck as a command line tool?

**Comment by attilavago** [comment]
Wow, you're fast! :)) Thanks for checking on the that. I have notified my colleague who is running it on a server to try and update it with the absolute latest release. Once that has been done, I will retest and get back to you. We use the GUI version.

**Comment by attilavago** [comment]
Hi @rdeltour :) You were right. Seems we did not quite have the absolute latest release. Error does not appear any more. Thanks for helping with this.

**Comment by rdeltour** [comment]
OK, good!
