### ISSUE TITLE
RSC-007 - what is missing?

### ISSUE THREAD

**Issue by mjhea0** [IDPF/epubcheck#667]
No idea even where to start with debugging this. Need more info!

```sh
➜  book1 git:(master) ✗ make epubcheck
epubcheck build/books/RealPythonPart1.epub
Validating using EPUB version 2.0.1 rules.
ERROR(RSC-007): build/books/RealPythonPart1.epub/ch016.xhtml(121,919): Referenced resource could not be found in the EPUB.

Check finished with errors

epubcheck completed
make: *** [epubcheck] Error 1
```

**Comment by jstallent** [comment]
Go to line 121 in ch016.xhtml, and find the 919th character. That will be
the general location of the error, probably a broken link or an image that
is not included in the file.

---------------------------------------------------------------------------------------------------

*JOSHUA TALLENT*   |  Director of Outreach and Education
joshua@firebrandtech.com
978-225-2757
www.firebrandtech.com
www.ebookarchitects.com


*@jtallent*
*@firebrandtech*

*Save the date! Firebrand's Community Conference is Sept. 27-29, 2016!*

Pre-flight your EPUB files with FlightDeck. Validation, Retailer Acceptance
Grid, Metadata Editing, and more!
http://eBookFlightDeck.com <http://ebookflightdeck.com/>

**Comment by mjhea0** [comment]
thanks!
