### ISSUE TITLE
Illegal characters in XML output

### ISSUE THREAD

**Issue by bitsgalore** [IDPF/epubcheck#670]
While processing an encrypted EPUB with Epubcheck 4.0.1 (with output to XML format), I ended up with the following output file:

<https://github.com/KBNLresearch/epubPolicyTests/blob/master/epubcheckout/4.0.1/epub20_encryption_binary_content.xml>

Line 17 of the output file contains a warning about an illegal XHTML Named entity. However, this very entity (Unicode code point U+000B / 0xb) is included in the output file (line 17, column 81), which makes the output itself invalid XML!  This creates problems if the XML needs to be processed further down the line (in my case I want to run some Schematron rules on it).

For rights reasons I cannot share the original EPUB,  but I created a synthetic file that reproduces the problem at:

<https://github.com/KBNLresearch/epubPolicyTests/blob/master/build/epub20_encryption_binary_content.epub?raw=true>

(See also about control characters in XML: <https://www.w3.org/International/questions/qa-controls.en.php>)

**Comment by rdeltour** [comment]
Ah, good catch. Thanks for the sample file!
