### ISSUE TITLE
Valid email address is reported as invalid

### ISSUE THREAD

**Issue by Matt-1** [IDPF/epubcheck#671]
I have an epub that contains
`<a href="mailto:M_H/SMI/SE%SMI@smi.ki.se">M_H/SMI/SE%SMI@smi.ki.se</a>` (email address slightly changed  for anonymity). While this indeed looks odd, it seems that both `/` and `%` are valid characters in an e-mail address according to the relevant RFCs. However, epubcheck 3.0.1 reports
`ERROR: ....epub/OEBPS/...html(5,5070): value of attribute "href" is invalid; must be a URI`

and epubcheck 4.0.1 reports
`ERROR(RSC-005): ...epub/OEBPS/...html(5,5070): Error while parsing file 'value of attribute "href" is invalid; must be a URI'.`
`ERROR(RSC-020): ...epub/OEBPS/...html(5,5070): 'mailto:M_H/SMI/SE%SMI@smi.ki.se' is not a valid URI.`

**Comment by mattgarrish** [comment]
From RFC 3986:

> Because the percent ("%") character serves as the indicator for percent-encoded octets, it must be percent-encoded as "%25" for that octet to be used as data within a URI.

**Comment by Matt-1** [comment]
Ah, of course! Thank you!

**Comment by vortexwebdesign** [comment]
Hi guys, i have had a similar issue. Error message is 
 Line 24 Error while parsing file "value of attribute "href" is invalid: must be a URI"
and Line 24 "http://" is not a valid URI.

Should I be looking for a hidden link? All links have been checked!

**Comment by tofi86** [comment]
hi @vortexwebdesign. please open a new issue for your request and add the following:

1. full epubcheck log / error message
2. valid html source code for the offending line
