### ISSUE TITLE
Epubcheck4 is *much* slower than epubcheck3

### ISSUE THREAD

**Issue by mclow** [IDPF/epubcheck#677]
Using a simple epub (10 chapters, small amount of text, 500 images), 
`java -jar -Djava.awt.headless=true ~/bin/ePubCheck/3.0.1/epubcheck-3.0.1.jar sample.epub` runs in 3 seconds, 
but `java -jar -Djava.awt.headless=true ~/bin/ePubCheck/4.0.1/epubcheck.jar sample.epub` takes 18 seconds.

That's 6x the time of version 3.

**Comment by tofi86** [comment]
This seems to be due to the increased sizes of third party libraries which need to be loaded first.

When using my "pagina EPUB-Checker" GUI, the first check is very slow as well. The following checks however, are multiple times faster because the libs are already cached...

**Comment by tofi86** [comment]
Closing this because there's not much we can do about it at the moment. EpubCheck 4.0 added a bunch of new dependencies and also a lot of new checks, so I'd call it side-effects...

Please feel free to reopen this issue if you think we should check on it again...
