### ISSUE TITLE
MathML warning about accessibility

### ISSUE THREAD

**Issue by pkra** [IDPF/epubcheck#678]
I've been wondering about the the following warning.

`MathML should either have an alt text attribute or annotation-xml child element.`

While I understand the motivation, this does not seem practical in today's state of AT. Is there actually an AT solution that would benefit from this? 

From my experience, if an AT does not support MathML it will neither support MathML's `alttext` attribute nor support finding something useful in annotation(-xml) elements. (Actually, I'm not sure if the warning's "alt text" means MathML's `alttext` or HTML's `alt` attribute but the same applies to `alt` afaik.)

It seems to me that this adds to the burden of content creators without any benefits.

**Comment by rdeltour** [comment]
This looks more like a spec issue; EpubCheck applies the conformance statements defined by EPUB for [MathML alternative content](http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-xhtml-mathml-alt).

Could you file the issue on [IDPF/epub-revision](https://github.com/IDPF/epub-revision/issues)?

**Comment by pkra** [comment]
Thanks for the pointer, @rdeltour. I'll file an issue.

From the spec, I'm guessing the answer to my parenthetical question is that the warning should say "alttext" instead of "alt text". Maybe that's still worth clarifying here.

**Comment by rdeltour** [comment]
> I'm guessing the answer to my parenthetical question is that the warning should say "alttext" instead of "alt text". Maybe that's still worth clarifying here.

Right I agree. FWIW I'm pretty sure it was the case at some point earlier. I'll make the change in the next release.
