### ISSUE TITLE
Line no. issue for linking missing cases(Fragment identifier)

### ISSUE THREAD

**Issue by shashikumar1** [IDPF/epubcheck#683]
For link missing cases exact value with line no not coming in this version

**Comment by tofi86** [comment]
Sorry, I don't understand what you mean.

**Comment by shashikumar1** [comment]
Means while running epubchecker and if we got error like "Fragment identifier" it will not gives us an references(line no.) to find exact issues.

**Comment by tofi86** [comment]
Unfortunately I cannot reproduce. Are you using version 4.0.1?

This is a missing fragment identifier in one of my epubs:
```
ERROR(RSC-012): my-ebook.epub/OEBPS/chapter2.xhtml(2,503): Fragment identifier is not defined.
```

There's a line number as well as a column number to locate the error.

Are you reffering to another error code?
