### ISSUE TITLE
ID Pattern issue not available

### ISSUE THREAD

**Issue by shashikumar1** [IDPF/epubcheck#684]
Before this version checker are checking the id way as like as XML but now it will not giving this errors

**Comment by tofi86** [comment]
Sorry, I don't understand what you mean.
please add an example!

What was the error message before with the old epubcheck?

**Comment by tofi86** [comment]
This has been answered by @mattgarrish in https://github.com/IDPF/epubcheck/issues/757#issuecomment-300774121:

> HTML5 does not require that IDs be valid XML IDs.

So if you're checking EPUB 3 books with HTML 5 this is perfectly fine.
