### ISSUE TITLE
Functional translation.

### ISSUE THREAD

**Issue by victorfcm** [IDPF/epubcheck#685]
Hi, my name is Victor Martins, i'm a brazilian developer.

My team had translated the MessageBundle.properties file, but, I can't use it to translate the messages, I've tried to put as MessageBundle_br.properties in the project, but nothing happend. I've tried to use the -l and -c flags, but isn't working too, the last try that I've did, is to remove the original MessageBundle.properties and overwrite with mine. But then, when I try to install, maven reports a lot of problems, like: "The message should be: $x but was: $y"..

How can I translate the output?? I really have tried a lot of things and none seems to work.

Thank you, and sorry about that ticket, I can't get an answer on google or stackoverflow.

**Comment by tofi86** [comment]
Please read the wiki entry for translating epubcheck messages: https://github.com/IDPF/epubcheck/wiki/Translating

**Comment by tofi86** [comment]
Also note, that there is no such language code `br`.
You don't speak _brazil_, you speak _Brazilian Portuguese_ which has the language code `pt-BR`.
So you need to name the massage files `messages_pt_BR.properties`, etc...

**Comment by victorfcm** [comment]
I've already read it, a lot of... I don't want to contribute, I don't want to use Transifex, I just want to do it manually.

And so I did it, overwriting the MessageBundle.properties file, but the messages still in english..

**Comment by tofi86** [comment]
Okay, so please make sure you name the message files correctly (see my comment above).

**Comment by victorfcm** [comment]
I've did it, and still not working, i've tried calling, again, with -c and -l flag, and nothing changes.

I also, edited the .tx/config to pt_BR, to test.

Man, please, tell me, how can I translate the output to a json?

Is that possible?..

**Comment by victorfcm** [comment]
And yes, I already use the -j option to output to a json file, the problem is to translate the messages

**Comment by tofi86** [comment]
The options `-l` and `-c` have nothing to do with translating epubcheck messages.

If you want to use translated messages, you have to build the `epubcheck.jar` with maven from the sources and add your translated message properties files before the `mvn clean install`.

If your system language (!!!) then equals `pt-BR` you should see your translated portuguese messages when running `java -jar epubcheck.jar`.
If you don't see them or if your system language is english, then you have to call epubcheck.jar with additional parameters: `java -Duser.lang=pt -Duser.country=BR -jar epubcheck.jar` to simulate a `pt-BR` environment.

**Comment by victorfcm** [comment]
Ohh, now I get it.

Bro, I'm not a java dev, so I would never know this answer exists. I HIGHLY RECOMMEND, that you put this answer on the documentation.

My sys. is in en-US, because it's an foregin server, how can I imagine that you just tell me?

You really need to put this on the docs bro.. 

Thank you for your time, and help. I'll try this, but should work!

Be more patient next time ;)

**Comment by victorfcm** [comment]
Okay, I've tried now:

Created the MessageBundle_pt-BR.properties (I also created _pt_BR to test)
Put it into src/main/resources/com/adobe/epubcheck/messages/
Ran mvn clean install
And then, used the command java -Duser.lang=pt -Duser.country=BR -jar target/epubcheck.jar ../epubs/188.epub

And the RSC-012 message keep comming: Fragment identifier is not defined.

But in the MessageBundle that I've created, the RSC_012 is correctly translated.

Anything more?..

**Comment by victorfcm** [comment]
Okay, found it.

Should be: -Duser.language=pt, and not: -Duser.lang=pt

PLEASE, PUT THAT INTO YOUR DOCS! MORE PEOPLE CAN BE LOOKING FOR THIS!!!

**Comment by tofi86** [comment]
Added this on the wiki page:
https://github.com/IDPF/epubcheck/wiki/Translating#testing
