### ISSUE TITLE
BitmapChecker.ImageHeuristics looks like it should be a public class?

### ISSUE THREAD

**Issue by jajessup** [IDPF/epubcheck#686]
//jaj private class ImageHeuristics
```
  public class ImageHeuristics
  {
    public int width;
    public int height;
    public long length;

    public ImageHeuristics(int width, int height, long length)
    {
      this.width = width;
      this.height = height;
      this.length = length;
    }
  }
```

**Comment by tofi86** [comment]
@jajessup wrote in #689:
> Thanks Tobias, may you could look at this one also – it’s in the same file: It just needs to visibility change from private to public. I say this because the object type is being returned from a “Public” function in the same file.

Do you need the information in an API or why do you need it to be `public`?

I don't know why @santoch made the class `private` (introduced in c74bc7080e8057231c536c9d0fd267bfb8846cb2), but he's probably the one who should take a look if any...

**Comment by jajessup** [comment]
Was attempting to create a .NET library wrapper out of it using IKVM and IKVM doesn’t know what to do with a public method that returns a private object.

**Comment by tofi86** [comment]
Seems to be a valid point, though I would like @santoch to decide this anyways...

**Comment by tofi86** [comment]
@jajessup answered in ticket #663 by mistake:
> Tobias, that object is declared in the same file as the public method that returns it. I’m not a java expert but beside IKVM, it didn’t look right having a “Public” method returning a “Private” object. If a “Public” method is returning a object, that object should be declared “Public” also. This just looks like a simple oversight.

@santoch answered in ticket #663 by mistake:
> Yes, it was an oversight.  My apologies.

@jajessup answered in ticket #663 by mistake:
> No problem. Thanks for your efforts!
