### ISSUE TITLE
BitmapChecker -> ImageInputStream not closed on image file validation.

### ISSUE THREAD

**Issue by jajessup** [IDPF/epubcheck#689]
This results in image files being locked and not deleted after validation. We noticed this in the temp folder of Tomcat.

**Comment by jajessup** [comment]
Ran into this in our production system.

**Comment by tofi86** [comment]
Should be fixed now. Thanks for reporting.

**Comment by jajessup** [comment]
Thanks Tobias, may you could look at this one also – it’s in the same file: It just needs to visibility change from private to public.

 

I say this because the object type is being returned from a “Public” function in the same file.

 

 <https://github.com/IDPF/epubcheck/issues/686> BitmapChecker.ImageHeuristics looks like it should be a public class?
