### ISSUE TITLE
ePub filesize limit

### ISSUE THREAD

**Issue by michael-igp** [IDPF/epubcheck#693]
Hi,

Is there a epub file-size limit that a epub should be created at? I have a epub which is more than 2GB size.

And when I validate it locally using the epubcheck 4.0.1 it throws the below error:

====================
FATAL(PKG-008): NOID.epub/NOID.epub(-1,-1): Unable to read file 'invalid CEN header (bad signature)'.

Check finished with errors

epubcheck completed
====================

Thanks,
Michael

**Comment by rkwright** [comment]
Sounds (sic) like a 32 bit signed int issue.

**Comment by michael-igp** [comment]
Okay. Did the unzip and zip again and this time no errors.

**Comment by AntonBolfing** [comment]
Besten Dank für Ihre Nachricht.

Ich bin bis am Dienstag, dem 5. Juli 2016 abwesend und kann Ihre Nachricht erst ab dann wieder bearbeiten. Ihre Email wird nicht weitergeleitet.
In dringenden Fällen wenden Sie sich bitte an Herrn Bernhard Heinser: bernhard.heinser@access-for-all.ch

Beste Grüsse

Anton Bolfing

*******************************************************

Thank you for your message.

I'm out of office until Tuesday, July 5, 2016.  I will not respond to your email until then.

Best regards

Anton Bolfing
