### ISSUE TITLE
USAGE asks for existing TOC reference

### ISSUE THREAD

**Issue by jenstroeger** [IDPF/epubcheck#694]
I'm trying to make sense of the following usage comment:

`USAGE(OPF-058): foo.epub/OEBPS/toc.xhtml(-1,-1): Spine item has no TOC entry reference.`

What does this mean? The `toc.xhtml` is referenced in `<spine>` and therewith in the `<manifest>`, as well as in the `<guide>` of the content.opf. It even references itself in the actual TOC (just to be sure). How do I quieten this comment?

**Comment by GarthConboy** [comment]
OPF-058 USAGE Spine item has no TOC entry reference. Every spine item in
the manifest should be referenced by at least one TOC entry.


It would like all <spine> items to be referenced from the Nav file.

Best,
   Garth

**Comment by jenstroeger** [comment]
The [issue](https://github.com/IDPF/epubcheck/issues/694) is also being discussed in [this Google group](https://groups.google.com/forum/#!topic/epubcheck/DLew2ao825I). Closing this one.
