### ISSUE TITLE
no epubcheck.jar in unzipped file for epubcheck-4.0.1

### ISSUE THREAD

**Issue by deborah-ufw** [IDPF/epubcheck#697]
Hi, I downloaded this git repo as a zip.

Followed instructions elsewhere to install java jre and set and confirm environment PATH.

ran 

    java -jar epubcheck.jar path-to/myfile.epub

got error

    java.util.MissingResourceException: Can't find bundle for base name com.adobe.epubcheck.util.messages,

after searching, found that the epubcheck.jar may have been separated from the library in the archive, and checked the archive.

The extracted zip archive does not contain the file, epubcheck.jar.

???

This process is painful.

**Comment by mattgarrish** [comment]
You don't want to download the github repository, as it contains the unbuilt sources.

You need to download the latest build here:
https://github.com/IDPF/epubcheck/releases/tag/v4.0.1

**Comment by tofi86** [comment]
This is also the 2nd section in the README file (which is displayed on the front page of this repository!):

> ## Downloads

> Check the [releases page](https://github.com/IDPF/epubcheck/releases) to get the latest distribution.

> [EpubCheck 4.0.1](https://github.com/IDPF/epubcheck/releases/tag/v4.0.1) is the latest recommended version to validate both EPUB 2 and 3 files.
