### ISSUE TITLE
mvn install error - "The goal you specified...but there is no POM in this directory"

### ISSUE THREAD

**Issue by deborah-ufw** [IDPF/epubcheck#698]
after not finding epubcheck.jar in the un-zipped file, I followed another nightmarish trail of instructions and errors to get Maven installed with install verified, then ran "mvn install" in terminal on the unzipped folder, epubcheck-4.0.1.  

Now there is another immense error concerning a missing file - Google not helping, because in fact, the file isn't there. 

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.086 s
[INFO] Finished at: 2016-07-13T21:14:47-07:00
[INFO] Final Memory: 6M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (path-to/epubcheck-4.0.1). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
```

Interestingly, the epubcheck.jar does appear after this error.

**Comment by tofi86** [comment]
If you still want to build the `epubcheck.jar` froum the uncompiled sources after we pointed you  to the releases page in #697, then please provide the whole maven logfile.

The build process for the epubcheck project is described in the project wiki (see main navigation above): https://github.com/IDPF/epubcheck/wiki and there on a separate page https://github.com/IDPF/epubcheck/wiki/Build

If this still fails, make sure you downloaded the correct sources and your epubcheck folder contains the file `pom.xml`.

----

Now I see that you say *"on the unzipped folder, epubcheck-4.0.1"* – but if you download the epubcheck sources from this repository, the ZIP file and folder is named `epubcheck-master` and it contains the `pom.xml`.

If you instead downloaded the `epubcheck-4.0.1.zip` from the releases page, you already got the built `epubcheck.jar` and there is no need to build it. You can just run `java -jar epubcheck.jar` from this folder...

**Comment by tofi86** [comment]
Closing this as outdated.

Please feel free to reopen this issue if you think we should check on it again...

**Comment by Richo40** [comment]
am getting that error too..

**Comment by tofi86** [comment]
@Richo40 you cannot run `mvn install` from a ZIP download. You need to clone the complete repository with git, then go into the directory in Terminal and run the commands.

**Comment by eliohb** [comment]
I have clone the complete repository with git, then go into the directory AgreementMaker-OSGi in Terminal and run the commands: mvn install the following error appears:
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  42.477 s
[INFO] Finished at: 2019-02-25T22:35:42+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project AgreementMaker-BatchMode: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Toshiba\Desktop\agreementmaker-master\AgreementMaker-OSGi\AgreementMaker-BatchMode\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :AgreementMaker-BatchMode

any advice

**Comment by rdeltour** [comment]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project AgreementMaker-BatchMode

Wrong issue tracker I guess? This is the repository for the EPUBCheck project, not AgreementMaker 😉

**Comment by sherrif10** [comment]
am getting the same issue but am trying to execute mvn to be able to create projects but seems j hae alot of configuaretions to first deal with, j actualy tried to set the directory where settings.xml should be placed but still j get the same isuue
