### ISSUE TITLE
<br /> tag that is not enclosed in a <p> tag gives error.

### ISSUE THREAD

**Issue by dteviot** [IDPF/epubcheck#700]
This XHTML fragment 
```xhtml
<body>
    <p>Some Text</p>
    <br />
    <p>More Text</p>
</body>
```
gives the error message 
> Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.

This XHTML fragment does not
```xhtml
<body>
    <p>Some Text</p>
    <p><br /></p>
    <p>More Text</p>
</body>
```

**Comment by mattgarrish** [comment]
If you're creating an EPUB 2, then that's correct. The br element isn't allowed as a child of the body in XHTML 1.1.

It's not an error in HTML5, and I can't reproduce in a conforming EPUB 3 publication.

**Comment by dteviot** [comment]
@mattgarrish

Thanks for the response.
