### ISSUE TITLE
Content model of <rp>

### ISSUE THREAD

**Issue by zcorpan** [IDPF/epubcheck#703]
We're considering changing the content model of `rp` in the HTML standard, see
https://github.com/whatwg/html/issues/1689

> FYI, the most of HTML ruby usage today is in EPUB. EPUB has a validation tool called epubcheck, I'm not sure if it checks DTD for XHTML or not, nor if this change results in the change to DTD, but many stores such as Apple iBooks does not accept content that fails epubcheck, so it's a small possible risk.

.

> For epubcheck it looks like this line would need a change if they want to match up with the spec:
> https://github.com/IDPF/epubcheck/blob/989595ba3aaf84a1735d46f248e98eb37944d12d/src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/html5-phrasing-30.rnc#L133

Please advice if you think the spec change is acceptable, or if you have any concrete examples of content that uses elements in `rp`. Thanks!

**Comment by rdeltour** [comment]
thanks @zcorpan for the heads-up.

> Please advice if you think the spec change is acceptable, or if you have any concrete examples of content that uses elements in rp.

I created idpf/epub-revision#854 to track the discussion with the EPUB WG.

As for EpubCheck, we generally try to strictly follow the EPUB spec, which follows W3C's HTML. Now, if there are no concrete use cases of elements in `rp` and we know the content model is to change, we can of course take the liberty to update our schemas!

**Comment by tofi86** [comment]
Closing this as this is not a matter of EpubCheck at the moment.
If the HTML schema gets updated with EPUB 3.1 we'll implement this sooner or later anyways...
