### ISSUE TITLE
For fixed layout title

### ISSUE THREAD

**Issue by shashikumar1** [IDPF/epubcheck#704]
We got below error while uploading epub into iTune Producer but epubchecker not able to catch this..

ERROR ITMS-9019: "Fixed layout books must identify the start of the bookΓÇÖs main content by including a guide (EPUB 2) or Landmarks (EPUB 3), or provide a custom sample. For more information see the iBookstore Asset Guide in the Deliver Your Content module on iTunes Connect." at Book

**Comment by rdeltour** [comment]
Including a guide or landmarks is not mandated by the EPUB spec. EpubCheck does not checks vendor-specific constraints.

Closing as invalid, feel free to reopen or comment if you disagree.
