### ISSUE TITLE
Guide reference error - invalid content type?

### ISSUE THREAD

**Issue by ltuch** [IDPF/epubcheck#705]
I have an epub which has the following entry in the guide:
`<reference type="cover" title="Cover Image" href="images/cover.jpg"/>`

In the manifest there is a corresponding entry:
`<item id="img_1" href="images/cover.jpg" media-type="image/jpeg"/>`

When this is run through validation I get the following error:
`Guide references '%1$s' which is not a valid 'OPS Content Document'.`

I believe the reason this error is being generated is because it is not one of the allowed types - application/xhtml+xml or image/svg+xml.

From a quick look at the epub specifications I could not find any restrictions on the content type of the items referenced in the guide (http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.6). The only possible restriction I can see is on the item media type, and the media-type of image/jpeg seems to one of the allowed types (http://www.idpf.org/epub/30/spec/epub30-publications.html#tbl-core-media-types).

Is the error generated here a spurious error?

**Comment by jstallent** [comment]
The error is correct. The spec (in the location you linked) states: "Each reference must have an href attribute referring to an OPS Content Document included in the manifest...". The link must point to a content document, and a JPG image is not a Content Document as defined in the OPS spec (http://www.idpf.org/epub/20/spec/OPS_2.0.1_draft.htm#Section1.4.1.2). You need to point to the cover image HTML file.

**Comment by rdeltour** [comment]
@jstallent is right, I'm closing the issue (feel free to reopen or comment if you disagree).
