### ISSUE TITLE
warning on unused CSS selectors

### ISSUE THREAD

**Issue by ousia** [IDPF/epubcheck#715]
Many thanks for your excellent work with epubcheck.

I have a suggestion improvement. Would it be possible that epubcheck warns on unused CSS selectors, so that they may be safely removed from the CSS file?

**Comment by tofi86** [comment]
Thanks, @ousia!

Regarding your question: as this is not part of the EPUB specification and is quite hard to check (due to the cascading concepts of CSS) I think it's not in the focus of the EpubCheck development at the moment... Sorry.

**Comment by ousia** [comment]
@tofi86, I cannot code (otherwise, I’d have provided a patch myself 😉).

I thought it wasn’t hard to implement the same matching heuristics that a browser has to deploy in order to apply the CSS properties.
