### ISSUE TITLE
attribute "start" not allowed

### ISSUE THREAD

**Issue by 1manfactory** [IDPF/epubcheck#739]
When converting to epub and checking this:

```
<ol start="2">
<li>
```

I get the following error:

> Error while parsing file 'attribute "start" not allowed here;

I tried to make head or tail out of this solution: http://maxdesign.com.au/articles/ordered-lists/

But I can't make it work.

Is this error really an error?

**Comment by mattgarrish** [comment]
If you created an EPUB 2 file, yes, it's an error. The start attribute is not valid in XHTML 1.1.

**Comment by tofi86** [comment]
@1manfactory can you tell us which EPUB version you're creating? As @mattgarrish stated: the start attribute is not supported in XHTML 1.1 (EPUB 2) but it is valid in HTML 5 (EPUB 3).

So if you have an EPUB 2 the error is correct and we'll close this issue.

**Comment by tofi86** [comment]
Closing this because of missing feedback from original author @1manfactory
