### ISSUE TITLE
Is the reference type "seriespage" broad enough?

### ISSUE THREAD

**Issue by bbapp** [IDPF/epubcheck#746]
Currently, there's a draft for a new reference type called "seriespage." (A "[m]arketing section used to list related publications." ) But to me, "seriespage" suggests books within a franchise or shared-universe of stories as opposed to various works by an author (that could be totally unrelated). Usually books end with something like "Also By [The Author]" followed by their most recent or famous books. 

Could/should "seriespage" be used for that purpose or do we need something else? 

P.S. I didn't know where else to post this. Is there a formal process for offering bug reports and suggestions for the EPUB spec?

**Comment by mattgarrish** [comment]
A list of titles by the same author is sometimes called a card page, but card page and series page are really just the same thing. It all depends on how formally you want to define a series.

As far as I'm aware, publishers don't make a semantic distinction between the books listed on the page as it's just a marketing piece. Adding another semantic would be proliferation without much obvious benefit.

But questions like this are best asked in the epub revision issue tracker: https://github.com/IDPF/epub-revision/issues

Feel free to open there if you feel strongly it needs reconsideration.
