### ISSUE TITLE
Invalid URI

### ISSUE THREAD

**Issue by leojarrabi** [IDPF/epubcheck#749]
I am getting this error: 
ERROR(RSC-020): 9781315354422.epub/OEBPS/Text/chapter12.xhtml(177,466): 'http://dx.doi.org/10.1002/1521-4141(2002010)32:10<2888::AID-IMMU2888>3.0.CO;2-F' is not a valid URI. 

I can't send the actual file because it is owned by the client and protected by a copyright, but here is the part where the code is used:

`<p id="ref12_60" class="ref">Manzotti, C. N. et al. Inhibition of human T cell proliferation by CTLA-4 utilizes CD80 and requires CD25+ regulatory T cells. Eur J Immunol 32, 2888–2896, doi:<a href="http://dx.doi.org/10.1002/1521-4141(2002010)32:10&#60;2888::AID-IMMU2888&#62;3.0.CO;2-F" class="uri">10.1002/1521-4141(2002010)32:10&#60;2888::AID-IMMU2888&#62;3.0.CO;2-F</a> (2002).</p>`

I checked the web link and it is an active link.

**Comment by mattgarrish** [comment]
The greater than and less than signs have to be percent encoded:

> http://dx.doi.org/10.1002/1521-4141(2002010)32:10%3C2888::AID-IMMU2888%3E3.0.CO;2-F

They fall outside the set of unreserved characters defined in RFC3986, and are part of the path percent-encode set in the [URL Standard](https://url.spec.whatwg.org/#path-percent-encode-set).

The url may well work in a browser using character references, but that doesn't make it valid. You're relying on the user agent interpreting it properly, which isn't guaranteed.

**Comment by leojarrabi** [comment]
Thank you very much, that resolved the problem.

**Comment by YadavRavi2002** [comment]
Hi All,

In one of the ePubs, a telephone number had been incorrectly attributed as
an href. Please see below:

<a href="tel:+31(0)71%205144%20233">071 5144 233</a>

However, this error was not picked up by the ePub checker version 4.0.2.
Could you include this in the future release?

Warm regards,

Ravi

--

Ravi Yadav | Senior Software Engineer

ravi.yadav@dk.com
T +91-120-4689740

DK 3rd Floor, Mindmill Corporate Tower, Plot 24A,
Sector 16A, Film City, Noida, India, 201301

www.dk.com
<http://www.google.com/url?q=http%3A%2F%2Fwww.dk.com%2F&sa=D&sntz=1&usg=AFQjCNHHJYyRGmAwwZvZMbjr6d91WlntZQ>
DKinVideo <http://www.youtube.com/user/DKinVideo>

<http://www.youtube.com/user/DKinVideo>

**Comment by mattgarrish** [comment]
There's no restriction against the tel protocol in EPUB, and your example validates, so there isn't anything wrong with the current reporting.

Whether it should report non-standard protocols as info messages is a fair question, although I expect it's not a big problem and seems to lead down a road of increasingly cluttered info messages.

But as a point of etiquette, please open a new issue for new requests. Unless the developers notice the email alert from github, they're not going to see that you added a different issue to a closed item.
