### ISSUE TITLE
epub validated file

### ISSUE THREAD

**Issue by Ganesh26101991** [IDPF/epubcheck#752]
![epub](https://cloud.githubusercontent.com/assets/27720353/25118997/25014d4e-2436-11e7-9026-133745bc6134.jpg)

![Uploading error.jpg…]()
![Uploading error.jpg…]()

**Comment by Ganesh26101991** [comment]
![error](https://cloud.githubusercontent.com/assets/27720353/25119216/e015725e-2436-11e7-9861-9733e8d5dc60.jpg)

**Comment by Ganesh26101991** [comment]
plz resolve this error, replay soon

**Comment by tofi86** [comment]
Regarding your first screenshot: You cannot upload OPF files. The IDPF online EpubCheck only supports checking `.epub` files. If you want to validate `.opf` files you need to use the EpubCheck commandline tool.

Regarding your second screenshot: That's most likely an error in your ZIP mechanism. The path in the column "file" leads to the assumption, that you ziped your epub file twice...

**Comment by Ganesh26101991** [comment]
sir .opf  file not send, so will send .zip extension file

**Comment by Ganesh26101991** [comment]
what is zip mechanism

**Comment by Ganesh26101991** [comment]
what is epub check command line tool

how to do this  epub check command line tool

**Comment by tofi86** [comment]
> what is epub check command line tool
> 
> how to do this epub check command line tool

Please have a look in the EpubCheck Wiki for further instructions on how to run EpubCheck in your Terminal: https://github.com/IDPF/epubcheck/wiki



> sir .opf file not send, so will send .zip extension file

You're right, you uploaded `Ganesh.epub` file.
However, you cannot just rename `.zip` to `.epub`. You have to zip the EPUB contents in a specific order. Let me google that for you: http://lmgtfy.com/?q=how+to+zip+epub

Best explanation: https://ebookflightdeck.com/handbook/zipping

----

Anyways, this issue tracker is for issues with EpubCheck, it's not a support forum for EPUB questions.
If you're having trouble to create an EPUB file, please visit the community forum at http://idpf.org/forums/epub-3 and ask your question there...

**Comment by Ganesh26101991** [comment]
sir 
What is zip mechanism ?
does not solved this error
![error](https://cloud.githubusercontent.com/assets/27720353/25123157/03be4f56-2445-11e7-8ee7-8f799df679a9.jpg)

**Comment by tofi86** [comment]
> What is zip mechanism ?

One last time: You have to zip the EPUB contents in a specific order. Let me google that for you: http://lmgtfy.com/?q=how+to+zip+epub

Best explanation: https://ebookflightdeck.com/handbook/zipping

Again: This is NOT a support forum for questions on how to create an EPUB file!!
If you're having trouble to create an EPUB file, please visit the community forum at http://idpf.org/forums/epub-3 and ask your question there...
