### ISSUE TITLE
The difference between latest and previous version's result.

### ISSUE THREAD

**Issue by hosoya-m** [IDPF/epubcheck#757]
Hello,

I ran epubchecks of un epub file in different versions and older version seems to show a right result.
At older version's result is following.

`MAC-HOSOYA-M:epubcheck-3.0.1 hosoya$ java -jar epubcheck-3.0.1.jar /Users/hosoya/Desktop/fixed/20170206_forautomation/20170509/8443976911000000000Q.epub `
`Epubcheck Version 3.0.1`
``
`Validating against EPUB version 3.0`
`WARNING: /Users/hosoya/Desktop/fixed/20170206_forautomation/20170509/8443976911000000000Q.epub/OEBPS/toc.ncx: meta@dtb:uid content '{%%uid%%}' should conform to unique-identifier in content.opf: 'urn:8443976911000000000Q'`
`ERROR: /Users/hosoya/Desktop/fixed/20170206_forautomation/20170509/8443976911000000000Q.epub/OEBPS/Text/p00132.xhtml(11,61): value of attribute "id" is invalid; must be an XML name without colons`
``
`Check finished with warnings or errors`

The latest version's (4.0.2) one is,
`MAC-HOSOYA-M:epubcheck-4.0.2 hosoya$ java -jar epubcheck.jar /Users/hosoya/Desktop/fixed/20170206_forautomation/20170509/8443976911000000000Q.epub `
`Validating using EPUB version 3.0.1 rules.`
`INFO(RSC-022): /Users/hosoya/Desktop/fixed/20170206_forautomation/20170509/8443976911000000000Q.epub/OEBPS/Images/cover.jpg(-1,-1): Cannot check image details (requires Java version 7 or higher). `
`INFO(RSC-022): /Users/hosoya/Desktop/fixed/20170206_forautomation/20170509/8443976911000000000Q.epub/OEBPS/Images/p00001.jpg(-1,-1): Cannot check image details (requires Java version 7 or higher). `
`...`
`No errors or warnings detected.`
`epubcheck completed`

The parts in question of opf file, ncx, xhtml files are,
- opf
`<?xml version="1.0" encoding="utf-8"?>`
`<package xmlns="http://www.idpf.org/2007/opf" prefix="rendition: http://www.idpf.org/vocab/rendition/# ebpaj: http://www.ebpaj.jp/" unique-identifier="books" version="3.0" xml:lang="ja">`
`...`
`    <dc:identifier id="books">urn:8443976911000000000Q</dc:identifier>`
`...`

- ncx
`<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">`
`  <head>`
`    <meta name="dtb:uid" content="{%%uid%%}" />`
`...`

- p00132.xhtml
`...`
`  <body>`
`    <div class="main" id="0ead6ac30fff432bf463a908065267f8">`
`...`

I'm wondering the latest version has a problem in checking the error or warning above.
I would appreciate your reply in advance.

**Comment by mattgarrish** [comment]
The id error in the 3.0.1 checker was a mistake. HTML5 does not require that IDs be valid XML IDs.

The dtb:uid mismatch is currently only reported if you use the --usage flag. See https://github.com/IDPF/epubcheck/issues/669

**Comment by hosoya-m** [comment]
Mr. Garrish,
Thank you for your reply.
I tried the --usage flag, but it wasn't be reported, though I don't know the reason.
The following are all that's connected with opf or ncx.

- `USAGE(OPF-058): /Users/hosoya/desktop/fixed/20170206_forautomation/20170509/8443976911000000000Q.epub/OEBPS/toc.xhtml(-1,-1): Spine item has no TOC entry reference.`
- `USAGE(HTM-010): /Users/hosoya/desktop/fixed/20170206_forautomation/20170509/8443976911000000000Q.epub/OEBPS/toc.ncx(2,68): Namespace uri 'http://www.daisy.org/z3986/2005/ncx/' was found.`
- `USAGE(OPF-059): /Users/hosoya/desktop/fixed/20170206_forautomation/20170509/8443976911000000000Q.epub/OEBPS/toc.ncx(-1,-1): Spine item has no NCX entry reference.`

But now I understand the previous issue, so I would wait for either of the two suggestions there (https://github.com/IDPF/epubcheck/issues/669#issuecomment-270646511) would be taken in the next version.

I appreciate your comment.

**Comment by tofi86** [comment]
Closing this issue as author @hosoya-m is waiting for fix in #669

**Comment by hosoya-m** [comment]
I really appreciate your help for my question.

**Comment by tofi86** [comment]
This has been fixed with PullRequest #798 and will be included in the upcoming release v4.1. Please see #669 and #798 for discussion on the topic.
