### ISSUE TITLE
navigation doc nav elements without epub:type restricted

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#759]
According to the specification, only nav elements with an epub:type attribute have to follow the markup restrictions, but I noticed today that nav elements without epub:type generate errors if they don't follow the pattern.

**Comment by mattgarrish** [comment]
The schemas are kind of brutal in terms of fixing this. The best I can see, instead of tweaking the html5.nav model for all nav elements, we need to create a separate epub.nav definition that requires epub.type and restricts the model.

The headache is that the epub.type module contributes itself to the global xml attributes. The only way I can see to avoid a duplicate declaration is to override the attribute definition for the regular html5.nav definition so that only the individual xml attributes are added.

I'd make a pull request for this, but additional eyes would be welcome before doing so. Here's what I was able to make work in epub-nav-30.rnc:

```
   default namespace = "http://www.w3.org/1999/xhtml"
   namespace epub = "http://www.idpf.org/2007/ops"
   
   include "epub-xhtml-30.rnc" {   
        html5.nav.attlist &= html5.global.common.attrs & html5.xml.lang.attr? & html5.xml.base.attr? & html5.xml.space.attr?
   }
   
   html5.sections.class |= epub.nav
   
   epub.nav = element nav { epub.type.attr & html5.global.common.attrs & html5.xml.lang.attr? & html5.xml.base.attr? & html5.xml.space.attr? & epub.nav.content }
   epub.nav.content = html5.headings.class?, epub.nav.ol     
   
   epub.nav.ol = element ol { html5.ol.attlist & epub.nav.ol.content }
   epub.nav.ol.content = epub.nav.oli*
   
   epub.nav.oli = element li { html5.oli.attlist & epub.nav.oli.content }
   epub.nav.oli.content = html5.a.phrasing | ((html5.a.phrasing | html5.span), html5.ol)
```

**Comment by mattgarrish** [comment]
Also, technically it should be epub.nav.oli+ to address the clarification made in 3.1 that empty lists are not valid (applies equally to 3.0).

**Comment by mattgarrish** [comment]
I'm afraid the above isn't even enough to fully capture the issue.

In the extensions section, the spec says that other nav elements must have a heading and should have an epub:type, so additional schematron checks are going to be needed.

I'll see what I can do.

**Comment by tofi86** [comment]
If you need help with the schematron checks, let me know.

**Comment by tofi86** [comment]
oh, you already added schematron checks with #763. alrighty... ;-)

**Comment by tofi86** [comment]
PR #753 merged. Issue closed.
