### ISSUE TITLE
ncx pageTarget type not checked

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#761]
As noted in the samples repository issues (https://github.com/IDPF/epub3-samples/issues/11), the type attribute is not restricted to the values front, normal and special.

The rng definition is currently the very permissive:

```
			<attribute name="type">
				<text/>
			</attribute>
```

But should be an enumeration:

```
			<attribute name="type">
				<choice>
				    <value>front</value>
				    <value>normal</value>
				    <value>special</value>
				</choice>
			</attribute>
```

**Comment by tofi86** [comment]
Fixed in PullRequest #762. Please have a look.
