### ISSUE TITLE
Clone dosen't work behind corporate firewall

### ISSUE THREAD

**Issue by WSchindler** [IDPF/epubcheck#771]
It was quite easy to create my personal **epubcheck** fork in my Github account - to be able to experiment with damaging the master. I could also download it as a zip and extract it on my hard disk, but creating a **clone doesn't work** with any method or Git client because I'm sitting behind a very strict corporate firewall (which I don't have any influence to change) and all the necessary ports (e.g. 443) seem to be blocked. What would be the best method to upload files, to generate a pull request or asking for comments? How do you upload files into a specific directory? Thx for your kind assistance and patience!

**Comment by rdeltour** [comment]
> It was quite easy to create my personal epubcheck fork (…) but creating a clone doesn't work

I'm confused here: a clone _is_ a fork. Can you elaborate what you can and cannot do?

> What would be the best method to upload files, to generate a pull request or asking for comments? How do you upload files into a specific directory?

I'm afraid you can't upload files or create pull request if you can't have some kind of write access to github. You can try to configure the port and/or ask your corporate tech admins perhaps?

Otherwise, comments and code reviews are another form of perfectly acceptable contribution :-)

**Comment by mattgarrish** [comment]
I think he means cloning his fork to his desktop so he can work on it.

I don't know of any workaround other than to talk to your IT people or work on it at home. If you can't pull/push files, you're basically out of luck.

**Comment by tofi86** [comment]
You mentioned port 443 so you tried cloning with HTTPS protocol. This is a standard port and should be open in every firewall, otherwise you would not be able to view regular websites with sSL.
Anyways,  You could try to clone your fork of the epubcheck repository via the git/ssh protocol. There's a switch in the github GUI for that to choose between HTTP and Git/SSH. Probably that works...

**Comment by tledoux** [comment]
The right way to go is using https than should be enable by your firewall. However, you need to declare the proxy corporate to git. Depending on whether you need to authenticate or not you should add this information to the global configuration of git :
`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`
or
`git config --global http.proxy http://proxy.server.com:8080`

Then the command
`git clone https://github.com/WSchindler/epubcheck.git`
should work

Hope it helps

**Comment by WSchindler** [comment]
Many thanks for your feedback :) 

@mattgarrish correctly grasped my intention - having a local copy of my "epubcheck" fork on which I could work and which I could upload again.  

I tried the HTTPS and the SSH approach several times, the cloning to my local disk starts, makes some progress and then stops.  I would suppose that it is an issue of user rights on the proxy server. In my Internet settings on my Windows machine, I find an automatic configuration script *.pac so that I don't even know the URL of our corporate proxy server.

**Comment by WSchindler** [comment]
It looks that I finally managed to clone  the **epubcheck** repo to my hard disk. The decisive issue was to find out the IP of our proxy server by inspecting the automatic configuration script. Then the commands given by @tledoux worked as intended.  To check whether I could create a pull request, I created a tiny edit to a LoremIpsum content doc and posted it as a pull request which may be safely ignored or deleted.

Once again many thanks for your patience and kind assistance :)

**Comment by rdeltour** [comment]
Great 👍. I'll close the PR.

**Comment by KevinDanikowski** [comment]
For those who stumble across this post for SSL issue but it's actually not a proxy causing the issue, try `git config --global http.sslVerify false` (make sure you don't have a http.proxy setting in gitconfig or else it will still not work).
