### ISSUE TITLE
Output fails to validate against JHOVE XSD when using the ---out switch

### ISSUE THREAD

**Issue by bitsgalore** [IDPF/epubcheck#773]
For some EPUBs the `--out` switch results in XML output that fails to validate against the JHOVE XSD schema.

Here's an example output file (created with *Epubcheck* 4.0.2):

<https://gist.github.com/bitsgalore/7f7bb86e29bd89aa1bf706704a28e6cc>

I validated this file against the current Jhove XSD using: 

    wget http://hul.harvard.edu/ois/xml/xsd/jhove/jhove.xsd
    xmllint --noout -schema jhove.xsd epubcheckXSDError.xml

Result:

    epubcheckXSDError.xml:125: element values: Schemas validity error : 
    Element '{http://hul.harvard.edu/ois/xml/ns/jhove}values': Missing child element(s). 
    Expected is one of ( {http://hul.harvard.edu/ois/xml/ns/jhove}property, {http://hul.harvard.edu/ois/xml/ns/jhove}value ).
    epubcheck.xml fails to validate

The validation error is caused by the empty *values* element:

    <property>
        <name>References</name>
        <values arity="List" type="Property"/>
    </property>
    
According to the [JHOVE schema](http://hul.harvard.edu/ois/xml/xsd/jhove/jhove.xsd) it must contain one or more *property* or *value* elements). 

So far we've run into this issue with about 150 Epubs that were sent to us by external publishers. Because of copyright reasons I cannot make these Epubs publicly available, but I can provide a sample off-list; just drop me an email at johan.vanderknijff@kb.nl.

**Comment by tofi86** [comment]
@tledoux Thomas, can you have a look at this please?

**Comment by tledoux** [comment]
Hi @bitsgalore , your epubs must definitively have something weird. 
When there is no references in the epub, the References property should not be output (see [XmlReportImpl.java#L184](https://github.com/IDPF/epubcheck/blob/981aa18b0fea40aab8962d9330c14abb0fead3a9/src/main/java/com/adobe/epubcheck/util/XmlReportImpl.java#L184) )

I  will need a sample to correct this one. Will drop you a mail then.

**Comment by tofi86** [comment]
Thanks for reporting this @bitsgalore and thanks for the quick fix @tledoux! This has been merged to `master` with PR #774 and will be released with upcoming EpubCheck 4.1

**Comment by bitsgalore** [comment]
Brilliant, thanks @tledoux for solving this issue at such a short notice! Related to do this, is it possible at this stage to give an approximate indication of the foreseen release date of version 4.1? Knowing this would help us decide whether to wait for 4.1, or make a local patch ourselves of version 4.0.1 (which is what we're currently using in our workflow).

**Comment by tofi86** [comment]
You can follow the development process of version 4.1 here: https://github.com/IDPF/epubcheck/projects/2

There is no ETA for the release yet, but since @TzviyaSiegman recently took over the project leadership there's at least good project managament ;-) And I think 4.1 is planned to be released within the next month, max. 2 months.

Please note that we strongly recommend you use version 4.0.2 or at least apply some patches for the security issues fixed with 4.0.2 (details: https://github.com/IDPF/epubcheck/releases/tag/v4.0.2)

**Comment by bitsgalore** [comment]
@tofi86 thanks for clarifying this. And yes you're right about using 4.0.2 rather than 4.0.1. So if we're going to patch we'll do that based om 4.0.2.
