### ISSUE TITLE
OEBPS/Text/index_split_003.html	line 14	possition 32 ---  Error while parsing file 'attribute "value" not allowed here; expected attribute "dir", "id", "lang", "style", "title" or "xml:lang"'.

### ISSUE THREAD

**Issue by Subi11** [IDPF/epubcheck#793]
I don´t know. What its mean but its common error, when i want to try validate. Do you know how fix it ?

**Comment by tofi86** [comment]
Please give this issue a normal title and put the error message and your question in the description field. Then reopen this issue.

For now I'd say, you used a not-supported attribute on an element.

Please not that this issue tracker is not a support forum.
