### ISSUE TITLE
xhtml has clear design flaw w.r.t. <ol> element

### ISSUE THREAD

**Issue by mark4asp** [IDPF/epubcheck#823]
When writing a table of contents using the <nav epub:type="toc"> element, it is _impossible_ to avoid putting the table of contents inside an <ol>.  The problem with that is the primitive rendering engines of epub readers (mine, anyhow) will try to render it with numbers. No matter what css one uses to make the number vanish.  One cannot use a <ul> in place of the <ol>.  So one ends up adding a superfluous number column to one's table of contents.  Obviously, it should be possible to use the <ul> in place of the <ol> element. That would solve the issue.

**Comment by AntonBolfing** [comment]
Besten Dank für Ihre Nachricht.

Ich bin bis am Dienstag, dem 9. Januar 2018 abwesend und kann Ihre Nachricht erst ab dann wieder bearbeiten. Ihre Email wird nicht weitergeleitet.


Beste Grüsse

Anton Bolfing

*******************************************************

Thank you for your message.

I'm out of office until Tuesday, January 9, 2018.  I will not respond to your email until then.

Best regards

Anton Bolfing

**Comment by tofi86** [comment]
@mark4asp you need to enclose every html element in this comment field in backticks ` otherwise GitHub tries to render the HTML element.

**Comment by mattgarrish** [comment]
This isn't an issue for epubcheck. You'll need to report it in the [epub revision tracker](https://github.com/w3c/publ-epub-revision/issues) if you want a change, although this was discussed extensively in the 3.0 revision. ol is the semantically correct choice, as a table of contents cannot be reordered without changing its meaning.

Primitive as they may be, a reading system is not implementing the specification correctly if it renders numbers outside the spine:

> In the context of this specification, the default display style of list items within nav elements must be equivalent to the list-style: none property [CSS Snapshot]. Reading Systems must not show list item numbering on these lists when presenting the Navigation Document outside of the spine, regardless of their support for CSS.

http://www.idpf.org/epub/31/spec/epub-packages.html#sec-package-nav-def-model

If the problem occurs trying to re-use the navigation document in the spine, you can always abandon the re-use approach and make a plain old content document with whatever structures you like for inline reading.

**Comment by dauwhe** [comment]
For reading systems that don't support CSS normally used to suppress numbering on the `nav` element (like `nav ol { list-style-type: none; }`), we just add a class attribute to the `ol`. We can then suppress the numbering in even very old reading systems with `.foo { margin: 0; padding: 0; list-style-type: none; }`.
