### ISSUE TITLE
Epubcheck update?

### ISSUE THREAD

**Issue by Schokolader** [IDPF/epubcheck#826]
Hello, 

how to update epubcheck to version 4.0.2. ? 
I installed it with apt-get and also downloaded version 4.0.2 but when I look up the version with epubcheck -help it shows only 4.0.1. 
How can I update epubcheck to version 4.0.2. on an ubuntu server?

**Comment by tofi86** [comment]
Ubuntu does not offer the current EpubCheck version as apt package.
You should send a request to the package maintainer listet at https://packages.ubuntu.com/de/xenial/epubcheck (@ezhukov, afaik) to implement the latest security release 4.0.2. this may usually take some time (months, years).

In the meantime, you can download EpubCheck as stated in the Readme file: go to [Releases](https://github.com/IDPF/epubcheck/releases) and doenload the latest ZIP file and use EpubCheck with the command `java -jar epubcheck.jar your-book.epub`.
