### ISSUE TITLE
DL with DIV cause error

### ISSUE THREAD

**Issue by pkra** [IDPF/epubcheck#831]
E.g., the following example from the WHATWG HTML spec (which validates at https://validator.w3.org)

```
<dl>
 <div>
  <dt> Last modified time </dt>
  <dd> 2004-12-23T23:33Z </dd>
 </div>
 <div>
  <dt> Recommended update interval </dt>
  <dd> 60s </dd>
 </div>
 <div>
  <dt> Authors </dt>
  <dt> Editors </dt>
  <dd> Robert Rothman </dd>
  <dd> Daniel Jackson </dd>
 </div>
</dl>
```

leads to epubcheck 4.0.2 giving something like:

```
ERROR(RSC-005): /OEBPS/Text/ch2.xhtml(79,18): Error while parsing file 'element "div" not allowed here; expected the element end-tag or element "dt"'.
```

**Comment by pkra** [comment]
I suppose this is more of a question as I'm not sure if this is just a question of updating the validator or if epub3 is prohibiting this.

**Comment by pkra** [comment]
Oh, I think this may be resolved by #827. In that case, sorry for the noise.

**Comment by rdeltour** [comment]
Yeah, this was a rather recent change in the `dl`’s content model, which wasn’t there in HTML 5.0 (which is the basis for the current version of EpubCheck).

But we should definitely update the schemas, or better move to W3C’s validator.

This should be covered in #827 indeed.

**Comment by pkra** [comment]
Thanks, Romain!
