### ISSUE TITLE
Epub error 

### ISSUE THREAD

**Issue by prashant1688** [IDPF/epubcheck#834]
MathML should either have an 'alttext' attribute or 'annotation-xml' child element error how to solved

**Comment by rkwright** [comment]
@prashant1688 @rdeltour 
Hm.  My reading of the specs 
https://www.w3.org/TR/MathML3/chapter5.html
https://www.iso.org/schema/isosts/v1.1/doc/n-tre0.html
suggests that including either the alttext attribute or annotation-xml elements is a MAY and hence omitting them is not an error.  In which case, we might want to emit a warning.  But I could be misinterpreting the spec.  
But adding all that additional content, while perhaps desirable would be additional work and might end up dissuading people from using MathML at all.

**Comment by mattgarrish** [comment]
It comes from the 3.0.1 content documents spec:

> The alttext attribute on the m:math element should be used for this purpose primarily when shorter alternative text runs are sufficient. When more extensive alternative text is required, XHTML Content Document fragments should be used. (Note that Reading Systems query these two alternative text locations using a defined preference order.)

3.1 did away with these are normative requirements. Authors are only "encouraged" to provide a fallback image.

**Comment by tofi86** [comment]
Also see discussion in #678.

Hi @prashant1688, unfortunately this is the wrong place to ask questions about solving EpubCheck errors. This place is meant for reporting bugs in EpubCheck. This is not a bug.
As the error messages says, you have to add an`alttext` attribute to the mathml element.

Best,
Tobias
