### ISSUE TITLE
epub fail on epubchecker due to setting direction

### ISSUE THREAD

**Issue by coder4567** [IDPF/epubcheck#836]
Dear Sir, 
As we were testing our epub on the epub checker we got failure for using div element, as shown in the attached screenshot, the div are essential to set the direction to rtl.  I would like to raise this issue, and see how could it be solved, 
Thank you for your efforts, 

epub checker result:
![img_13032018_135558_0](https://user-images.githubusercontent.com/1804546/37706368-f3d54910-2d07-11e8-88e2-39a29ee60117.png)

**Comment by mattgarrish** [comment]
The problem is with your markup, not epubcheck. You're trying to put a div inside an element that doesn't allow divs as children, but not possible to say which from the snippet. Try switching to a span if you just want to change direction without changing the formatting.

**Comment by coder4567** [comment]
Thank you for your reply, in fact we used to do it before without facing any issue, div elements never caused an issue inside the body, and it is automatically inserted by sigil program which we used to make the ePub. 
 This is the content of the file causing the issue, kindly if you can direct me into the source of the error:


<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  
  <title></title>
</head>
<body>
<p></p>
<p style="text-align: right;">&#160;</p>
<p style="text-align: right;">&#160;</p>
<p style="text-align: right;">&#160;</p>
<p style="text-align: right;">&#160;</p>
<h1><div style="text-align: right;">طلب موسى بن طولون&#160;</div><div style="text-align: right;">ولاية الإسكندرية</div></h1>
<p style="text-align: right;">&#160;</p>
<p style="text-align: right;">كان موسى أخو أحمد بن طولون رجلًا فيه خير، فلمَّا حصلتْ الإسكندرية لأخيه، وهي بلد ثغر، أحبّ المقام بها، فسأل يعقوب أبا يوسف الكاتب، الذي كان ضمَّه الوزير إلى أحمد بن طولون عند رحيله إلى مصر أنْ يسأل أخاه في تقليده إيَّاها، وكانت بينه وبينه مودّة، فقال له: ابتدئ أنت بالقول، وأنا أكفيك إذا خلوت به، فخاطب أخاه على مضَض منه؛ لأنَّه كان لمَّا قَدِمَا البلد أمر فيه ونهى، كما يفعل الأخ الشقيق مع الشقيق، فثَقُل ذلك على أخيه، حتَّى إنَّه قصد قومًا كان أخوه يعتني بهم بالأَذية. </p>
<p style="text-align: right;">وأمسك موسى عمَّا كان يعمله ويحمل مسألته، فيخرج من البلد ولا يكون معه فيه لما بيَّنته. فلمَّا سأله ردّ عليه ردًّا ضعيفًا فأغضبه ذلك، فقال: تالله لقد أَيست منك ومن مرتبة أنالها بك في الدنيا، وإنَّما طلبتُ هذا البلد؛ لأنَّه ثغر من الثغور اخترتُ المقام فيه والتعبّد، فوعده بتقليده إيَّاه. </p>
<p style="text-align: right;">وكان أحمد بن طولون يتوقّع من يارجوخ إنفاذه إليه الكتبَ بولاية الثغور الشاميَّة، وقد رشَّح أخاه موسى لتقليده إيّاه طَرَسوس، فإنّها أجلُّ ممّا طلب منه، وأَسَرَّ ذلك إلى أنْ ترد الكتب به عليه، وأراد أحمد بن طولون بولاية أخيه طرسوس إحياء ذكره بالثغر؛ لأنَّه كان أغلب البلدان على قلبه محبةً، وآثرها عنده. </p>
<p style="text-align: right;">وعزم أحمد بن طولون على الخروج إلى الإسكندرية لمشاهدتها وتسلّمها، فسأل موسى أبا يوسف الكاتب معاودة أخيه في أمرها له، حسب ما وعده، فخاطبه في ذلك فوعده أيضًا. وخرج أحمد بن طولون إليها مُرابطًا، فرحًا بما حصل له منها، لمحبَّته للثغور لا غير، وكان ذلك في سنة ستٍ وخمسين ومئتين. </p>
<p style="text-align: right;">فحدث الواسطي أحمد بن محمد كاتبه عنه أنَّه قال لمَّا وردت عليه الكتب بردّ الأعمال الخارجة إليه: الحمد لله كثيرًا، وقال: تركنا لله - عزَّ وجلَّ - شيئًا واحدًا، عوّضنا منه أشياء أعظم منه وأجود وأحمد عاقبة. كانت نهاية ما وُعدنا به على قتل المُستعين بالله تقليد واسط، فَخِفْنَا الله - عزَّ وجلَّ - في قتله فلم نقتله، فعوَّضنا، جَلَّ اسمه، مصر وغيرَها. </p>
<p style="text-align: right;">فلمَّا قرب من الإسكندرية تلقَّاه إسحق بن دينار، وقد كان وقف على ما جرى، وتوَقَّع صرفه عنها، فخرج إليه حتى لقيه بأبعد المواضع. فلمَّا رآه ترجَّل له، وأعطاه بحق الرياسة عليه، فأحشم<sup><a class="note" href="../Text/Section0001_0043.xhtml#footnote-19" id="footnote-ref-19">[19]</a></sup> ذلك منه أحمد بن طولون وكان حييًّا، رقيق الوجه، فاستحيا منه أنْ يصرفه عن البلد فأقرّه عليه. </p>
<p style="text-align: right;">وجعل موسى يترقَّب من أخيه إنجاز وعده له، فلمَّا طال ذلك سأل أبا يوسف أيضًا المسألة، وقال له أبو يوسف: أيَّدَ الله الأمير، أخوك مُنتظِر لوعدك. فقال له: ويحك قد كان ما وعدتُ به، وتالله إنِّي لآمل له ما هو أجلُّ منه، وقد ترى ما صنعه هذا الرجل معنا من الجميل على مَحلّه أيضًا في نفسه، ولا والله ما يحملني وجهي أصرفُه عن عمله، فتلطَّف لي في أنْ تصرف رأي أخي عن هذا الأمر، وقُلْ له: إنَّ أخاك يرشِّحك إلى ما هو أجَلُّ من هذه المدينة، واحذرْ أنْ تطلعه على شيء ممَّا ذكرته لك من أمر ابن دينار. </p>
<p style="text-align: right;">فلمَّا سأله موسى عن الجواب عَرَّفه أنَّ أخاه يرشِّحه لمَا أجلُّ ممَّا طَلَبَهُ، فلم يَثْنه ذلك، وقال: ما أُريد سوى هذه المدينة، وهي أحبّ إليَّ من كلّ ناحية جليلة. فلمَّا رآه أبو يوسف لا ينتهي عنها كشف له الخبر، لمَا كان بينه وبينه من المودّة، ولأنَّهما كانا يجتمعان على التعجّب من مصادر أُمور أحمد بن طولون ومواردها، وأنَّ الحظَّ قد عمل له ما لم يقدّره، حتى إنَّه قد حسَّن قبيحه، وأصلح رديئه. </p>
<p style="text-align: right;">فاغتاظ موسى ممَّا حكاه له أبو يوسف، وصار إلى أخيه، وقال له: بخلتَ عليَّ بما لا مشقَّة عليك فيه، وخاطبه - بدالَّة الأُخوَّة - بكلام فيه غِلَظ بحضرة الناس، إلى أنْ قال له: ما أحسبكَ تخرج من الدنيا سالمًا، لقطعك لرحمك، وسوء نيَّتك، وتفضيلك غلمانك، ومن تختاره بسوء رأْيكَ على أقرب الناس منكَ، فلعن الله جوارك وأراحني منه. فأمر به فبُطح وضَربَه بيده مقارع يسيرة. فعاتب الناس موسى على ما خاطب به أخاه وقالوا له: ليس أخوك اليوم هو الذي تعهده وتعرفه، فوفِّه حقَّ الرئاسة، واطرح دالَّة الأُخوَّة، فلم يَقْبَل، وكان فيه لجاجٌ وكِبر نفس، فراسله في أنْ يكتب له جوازًا ليخرج عن البلد، فتغنَّم ذلك أحمد بن طولون منه ليريح قلبه منه، ومن دالَّته عليه، فكتب له الجواز وأمر له بمال كثير فلم يقبله، وخرج غضبان إلى طرَسوس، فقبض أحمد بن طولون على أبي يوسف وقال له: أظهرت لأخي ما أَمرتُكَ بسَتْرِه عنه، فأوحشتَ بذلك ما بيني وبينه، وأنفذه من الإسكندرية إلى المُطْبِق<sup><a class="note" href="../Text/Section0001_0043.xhtml#footnote-20" id="footnote-ref-20">[20]</a></sup> بمصر. </p>
<p style="text-align: right;"></p>
</body>
</html>


Thank you for your kind follow up

**Comment by mattgarrish** [comment]
If this is an epub 2 file, you can't have a div inside an h1.

**Comment by mattgarrish** [comment]
See the definition here: https://www.w3.org/TR/html/sections.html#the-h1-h2-h3-h4-h5-and-h6-elements

H1 only takes phrasing content.

Closing this issue.

**Comment by coder4567** [comment]
Thank you for your guidance, shall I raise an issue in sigil, for it's generating this case? or there is a way to contain it?

**Comment by mattgarrish** [comment]
If that's the program that introduced the markup, then yes, you'll want to report it to them.
