### ISSUE TITLE
ePub error message

### ISSUE THREAD

**Issue by shazzieb** [IDPF/epubcheck#839]
how do I fix epub error message This link uses the file:// URL scheme. This does not work with many e-book readers. Remove the file:// prefix and make sure the link points to a file inside the book

The above message appears in my file when converting - in Calibre - there are a page or two that have hyperlink web address. I checked the links and they are not broken. So why the message and how do I resolve it? I tried to delete the /// but nothing happens. I am new to html so please be gentle!

Thanks in advance Shazzieb

**Comment by tofi86** [comment]
Hi Shazzieb,

unfortunately this is the wrong place to ask questions about solving EpubCheck errors. This place is meant for reporting bugs in EpubCheck.

Somewhere in your Calibre EPUB there is some kind of link which begins with `file://`, probably a local resource (image, word, etc.) which you inserted into Calibre by Drag&Drop or somehow else. This is not allowed. You have to remove this link. If you don't know how to find it or how to fix it within Calibre, I'm afraid the EpubCheck community cannot help you with this. You better ask in the Calibre user forums.

Best,
Tobias
