### ISSUE TITLE
epub checker is not showing up any errors but finished validating with errors

### ISSUE THREAD

**Issue by prabhathulasi** [IDPF/epubcheck#844]
![err copy](https://user-images.githubusercontent.com/39266655/39997386-68f4afd4-57a0-11e8-9eef-b14cd24b4ab5.jpg)
please help me how to overcome this error
see the above pic it says  eub checks finished with errors or warnings but not showing up any error how to i validate this one #

**Comment by tofi86** [comment]
The screenshot is from my GUI program "pagina EPUB-Checker" and is not related to this project.
Can you please open a new issue over there at https://github.com/paginagmbh/EPUB-Checker/issues/new ? Thanks!

This project here is all about the "EpubCheck" commandline tool.

**Comment by prabhathulasi** [comment]
thanks man but just tell me how to clear the error man i created an epub file and when i try to validate it itss shows like this only

**Comment by tofi86** [comment]
First of all: It does NOT help if you just open another issue with the same question.

You should have read my first comment above and followed my advice! This project here is NOT the support forum for "pagina EPUB-Checker"!
