### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by ololoe** [IDPF/epubcheck#847]
>  ERROR(PKG-006): file.epub(-1,-1): Mimetype file entry is missing or is not the first file in the archive.

This message also occurs when the file is compressed. Please fix.

**Comment by tofi86** [comment]
It's not about compression. It's about the order of the compressed items.

If you use zip on the commandline you have to zip the mimetype first, uncompressed, creating the zip archive. Then in a second step you have to add the other EPUB resources, compressed. The mimetype file has to be the first entry and needs to be uncompressed.

If you just zip up a folder, this won't work and the EPUB is invalid with the message you mentioned above.

Closing this as invalid.
If you think you zipped the EPUB correctly, please feel free to reopen the issue and post a detailed description about how you zipped the EPUB file.

**Comment by ololoe** [comment]
> you have to zip the mimetype first, uncompressed

Yes! That's exactly what I'm talking about! The error message doesn't include the word "uncompressed"!

**Comment by tofi86** [comment]
If it's not the first entry in the ZIP file we cannot check whether it's compressed or not. So all we can say at this point is the message above: that the mimetype file is missing or not the first entry.

Sorry, we can't be more precise here.

**Comment by fabswt** [comment]
I was getting `Mimetype file entry is missing or is not the first file in the archive.` errors too and this is the first result on Google for it.

People getting started with working with EPUBs from the command-line may be happy to learn how to compress an epub folder into an epub file:

    zip -rX "../myprecious.epub" mimetype $(ls|xargs echo|sed 's/mimetype//g') -x *.DS_Store

This will place the `mimetype` file first in the archive, and zip anything else found in the folder (to the exclusion of the invisible `.DS_Store` files found on the Mac and which shouldn't be part of the epub.)

…or see a discussion of the topic here: [How to repack an epub file from command line](https://ebooks.stackexchange.com/questions/257/how-to-repack-an-epub-file-from-command-line).
