### ISSUE TITLE
Newcomer to this and validating epub for smashwords... error is 'September' is not an integer

### ISSUE THREAD

**Issue by phlanders** [IDPF/epubcheck#851]
Hi,

I am a newcomer to this and am attempting to verify an already made epub file with the validator smashwords provides a link to. I selected my file and the following error was generated, though precisely what it means ( how to decipher ? ) and how to rectify the issue, I do not know. The error is on Line 11, Position 13. The error is for the date-time... input string 'September' which it states is not an integer.

Where do I find this and how to correct it? I constructed the file in inDesign. Is there something that needs to be done to the source file?

**Please see below:**

Type | File | Line | Position | Message
-- | -- | -- | -- | --
ERROR | OEBPS/content.opf | 11 | 31 | Date value 'September' is not valid as per http://www.w3.org/TR/NOTE-datetime:[For input string: "September"] is not an integer.

**Comment by TzviyaSiegman** [comment]
Hi @phlanders 

Unfortunately, this is the wrong place to ask questions about solving EpubCheck errors. This place is meant for reporting bugs in EpubCheck.
You might try turning to the #eprdctn community on Twitter.
