### ISSUE TITLE
Enable Github App "WIP" to protect unfinished PR's

### ISSUE THREAD

**Issue by tofi86** [IDPF/epubcheck#855]
A couple of PR's use the "WIP" ("work in progress") term in the PR title to state that the PR is not ready to merge yet.

By installing the GitHub App ["WIP"](https://github.com/apps/wip) through a maintainer (@rdeltour?) the "build status" is set to pending until the "WIP" prefix is removed.

Shall we enable this App?

**Comment by rdeltour** [comment]
I installed it, let's see how it goes…

**Comment by tofi86** [comment]
Awesome, thanks! :)

We'll see whether it works with the next new pull requests coming in...
